#!/usr/bin/env python3
"""Add example sentences (ex, ex_cn) to each word entry in word_bank.dart."""

import re

filepath = r'C:\Users\JXS\.zcode\workspace\default\shuai_jiujiu\lib\data\word_bank.dart'

# ===== Junior word examples (lines 7-496, ~490 words) =====
junior_examples = {
    'the': ("The book is on the desk.", "这本书在书桌上。"),
    'be': ("I want to be a teacher.", "我想成为一名老师。"),
    'and': ("I like apples and oranges.", "我喜欢苹果和橙子。"),
    'a': ("She has a cat.", "她有一只猫。"),
    'to': ("I go to school every day.", "我每天去上学。"),
    'of': ("This is a cup of tea.", "这是一杯茶。"),
    'in': ("He lives in Beijing.", "他住在北京。"),
    'have': ("I have two sisters.", "我有两个姐妹。"),
    'it': ("It is a sunny day.", "这是一个晴天。"),
    'for': ("I waited for an hour.", "我等了一个小时。"),
    'not': ("I do not like snakes.", "我不喜欢蛇。"),
    'on': ("The book is on the table.", "书在桌子上。"),
    'with': ("She goes to school with me.", "她和我一起去上学。"),
    'he': ("He is my best friend.", "他是我最好的朋友。"),
    'as': ("He is as tall as his father.", "他和他爸爸一样高。"),
    'you': ("You are very kind.", "你非常善良。"),
    'do': ("What do you want to do?", "你想做什么？"),
    'at': ("I am at home now.", "我现在在家。"),
    'this': ("This is my pen.", "这是我的钢笔。"),
    'but': ("I am tired but happy.", "我很累但是很开心。"),
    'his': ("His name is Tom.", "他的名字是汤姆。"),
    'by': ("I go to school by bus.", "我乘公交车去上学。"),
    'from': ("She comes from China.", "她来自中国。"),
    'they': ("They are playing soccer.", "他们正在踢足球。"),
    'we': ("We are good friends.", "我们是好朋友。"),
    'say': ("She says hello to me.", "她向我问好。"),
    'her': ("I gave her a gift.", "我给了她一份礼物。"),
    'she': ("She is a student.", "她是一名学生。"),
    'or': ("Do you want tea or coffee?", "你想要茶还是咖啡？"),
    'an': ("She is an honest girl.", "她是一个诚实的女孩。"),
    'will': ("I will call you tomorrow.", "我明天会打电话给你。"),
    'my': ("This is my book.", "这是我的书。"),
    'one': ("I have one brother.", "我有一个哥哥。"),
    'all': ("All of us passed the exam.", "我们所有人都通过了考试。"),
    'would': ("I would like some water.", "我想要一些水。"),
    'there': ("There is a book on the desk.", "书桌上有一本书。"),
    'their': ("Their school is very big.", "他们的学校很大。"),
    'what': ("What is your name?", "你叫什么名字？"),
    'so': ("She was so tired that she fell asleep.", "她太累了以至于睡着了。"),
    'up': ("Please stand up.", "请站起来。"),
    'out': ("Let's go out for a walk.", "我们出去散步吧。"),
    'if': ("If it rains, I will stay at home.", "如果下雨，我就待在家里。"),
    'about': ("What about having lunch together?", "一起吃午饭怎么样？"),
    'who': ("Who is that girl?", "那个女孩是谁？"),
    'get': ("I get up at six every morning.", "我每天早上六点起床。"),
    'which': ("Which color do you like?", "你喜欢哪个颜色？"),
    'go': ("Let's go to the park.", "我们去公园吧。"),
    'me': ("Please help me.", "请帮帮我。"),
    'when': ("When do you get up?", "你什么时候起床？"),
    'make': ("My mother makes dinner every day.", "我妈妈每天做晚饭。"),
    'can': ("I can swim very well.", "我游泳游得很好。"),
    'like': ("I like reading books.", "我喜欢读书。"),
    'time': ("What time is it now?", "现在几点了？"),
    'no': ("I have no money.", "我没有钱。"),
    'just': ("I just finished my homework.", "我刚做完作业。"),
    'him': ("I saw him at the park.", "我在公园看见了他。"),
    'know': ("I know the answer.", "我知道答案。"),
    'take': ("Please take a seat.", "请坐下。"),
    'people': ("Many people like sports.", "很多人喜欢运动。"),
    'into': ("She went into the room.", "她走进了房间。"),
    'year': ("I am twelve years old.", "我十二岁。"),
    'your': ("Your bag is very nice.", "你的包很漂亮。"),
    'good': ("She is a good student.", "她是个好学生。"),
    'some': ("I want some water.", "我想要一些水。"),
    'could': ("Could you help me please?", "你能帮我一下吗？"),
    'them': ("I told them the story.", "我给他们讲了那个故事。"),
    'see': ("I can see a bird in the tree.", "我能看见树上有一只鸟。"),
    'other': ("We should help each other.", "我们应该互相帮助。"),
    'than': ("She is taller than me.", "她比我高。"),
    'then': ("First do your homework, then you can play.", "先做作业，然后你可以玩。"),
    'now': ("I am doing my homework now.", "我现在正在做作业。"),
    'look': ("Look at the blackboard.", "看黑板。"),
    'only': ("I only have one sister.", "我只有一个妹妹。"),
    'come': ("Come here, please.", "请过来一下。"),
    'its': ("The cat is eating its food.", "猫正在吃它的食物。"),
    'over': ("The game is over.", "游戏结束了。"),
    'think': ("I think it is a good idea.", "我认为这是个好主意。"),
    'also': ("She can also speak English.", "她也会说英语。"),
    'back': ("I will come back soon.", "我很快就回来。"),
    'after': ("Let's play after school.", "放学后我们玩吧。"),
    'use': ("May I use your pen?", "我可以用你的钢笔吗？"),
    'two': ("I have two apples.", "我有两个苹果。"),
    'how': ("How are you today?", "你今天怎么样？"),
    'our': ("Our school is beautiful.", "我们的学校很漂亮。"),
    'work': ("My father goes to work by car.", "我父亲开车去上班。"),
    'first': ("She came first in the race.", "她在比赛中得了第一名。"),
    'well': ("She sings very well.", "她唱得很好。"),
    'way': ("Can you tell me the way to the station?", "你能告诉我去车站的路吗？"),
    'even': ("She is even taller than her brother.", "她甚至比她哥哥还高。"),
    'new': ("I got a new bike.", "我得到了一辆新自行车。"),
    'want': ("I want to go home.", "我想回家。"),
    'because': ("I am happy because I passed the exam.", "我很高兴因为我通过了考试。"),
    'any': ("Do you have any questions?", "你有什么问题吗？"),
    'these': ("These books are mine.", "这些书是我的。"),
    'give': ("Please give me the book.", "请把那本书给我。"),
    'day': ("It is a beautiful day.", "这是一个美丽的日子。"),
    'most': ("Most students like summer vacation.", "大多数学生喜欢暑假。"),
    'us': ("Let us go to the library.", "我们去图书馆吧。"),
    'great': ("That's a great idea!", "那是个好主意！"),
    'tell': ("Tell me a story.", "给我讲个故事。"),
    'very': ("She is very kind.", "她非常善良。"),
    'girl': ("The girl is reading a book.", "那个女孩正在读书。"),
    'boy': ("The boy is playing soccer.", "那个男孩正在踢足球。"),
    'man': ("The man is a doctor.", "那个男人是一名医生。"),
    'woman': ("The woman is my teacher.", "那个女士是我的老师。"),
    'child': ("The child is crying.", "那个孩子在哭。"),
    'mother': ("My mother cooks delicious food.", "我妈妈做美味的食物。"),
    'father': ("My father is a policeman.", "我爸爸是一名警察。"),
    'brother': ("My brother plays basketball well.", "我哥哥篮球打得很好。"),
    'sister': ("My sister likes dancing.", "我姐姐喜欢跳舞。"),
    'friend': ("She is my best friend.", "她是我最好的朋友。"),
    'school': ("I go to school at seven.", "我七点去上学。"),
    'teacher': ("Our teacher is very nice.", "我们的老师很和蔼。"),
    'student': ("He is a good student.", "他是个好学生。"),
    'book': ("I like reading books.", "我喜欢读书。"),
    'pen': ("This is my pen.", "这是我的钢笔。"),
    'desk': ("There is a book on the desk.", "书桌上有一本书。"),
    'chair': ("Please sit on the chair.", "请坐在椅子上。"),
    'room': ("My room is clean and tidy.", "我的房间干净整洁。"),
    'door': ("Please close the door.", "请关上门。"),
    'window': ("Open the window, please.", "请打开窗户。"),
    'table': ("Put the book on the table.", "把书放在桌子上。"),
    'food': ("The food tastes delicious.", "这食物尝起来很美味。"),
    'water': ("I drink a glass of water every morning.", "我每天早上喝一杯水。"),
    'milk': ("I drink milk every day.", "我每天喝牛奶。"),
    'rice': ("We eat rice for lunch.", "我们午饭吃米饭。"),
    'meat': ("I like eating meat.", "我喜欢吃肉。"),
    'fruit': ("Eating fruit is good for health.", "吃水果对健康有益。"),
    'apple': ("I eat an apple every day.", "我每天吃一个苹果。"),
    'banana': ("Monkeys like bananas.", "猴子喜欢香蕉。"),
    'orange': ("She is eating an orange.", "她正在吃一个橙子。"),
    'color': ("What color is your bag?", "你的包是什么颜色？"),
    'red': ("The apple is red.", "这个苹果是红色的。"),
    'blue': ("The sky is blue.", "天空是蓝色的。"),
    'green': ("The grass is green.", "草是绿色的。"),
    'yellow': ("The sun is yellow.", "太阳是黄色的。"),
    'white': ("Snow is white.", "雪是白色的。"),
    'black': ("I have a black cat.", "我有一只黑猫。"),
    'big': ("This is a big house.", "这是一栋大房子。"),
    'small': ("The cat is small.", "这只猫很小。"),
    'long': ("She has long hair.", "她有长头发。"),
    'short': ("He is short but strong.", "他个子矮但很强壮。"),
    'tall': ("My brother is very tall.", "我哥哥很高。"),
    'old': ("This is an old building.", "这是一栋旧建筑。"),
    'young': ("She is young and beautiful.", "她年轻又美丽。"),
    'hot': ("The weather is hot today.", "今天天气很热。"),
    'cold': ("It is cold in winter.", "冬天很冷。"),
    'warm': ("Spring is warm.", "春天很温暖。"),
    'cool': ("It is cool in autumn.", "秋天很凉爽。"),
    'happy': ("I am happy to see you.", "我很高兴见到你。"),
    'sad': ("She feels sad today.", "她今天感到难过。"),
    'angry': ("Don't be angry with me.", "别生我的气。"),
    'tired': ("I am very tired after running.", "跑步后我很累。"),
    'hungry': ("I am hungry. Let's eat.", "我饿了。我们吃饭吧。"),
    'thirsty': ("I am thirsty. I need water.", "我渴了。我需要水。"),
    'beautiful': ("The flowers are beautiful.", "这些花很美。"),
    'ugly': ("That is an ugly chair.", "那是一把难看的椅子。"),
    'rich': ("He is a rich man.", "他是个有钱人。"),
    'poor': ("We should help poor people.", "我们应该帮助穷人。"),
    'easy': ("The exam was easy.", "考试很简单。"),
    'difficult': ("Math is difficult for me.", "数学对我来说很难。"),
    'important': ("It is important to study hard.", "努力学习很重要。"),
    'different': ("We are in different classes.", "我们在不同的班级。"),
    'same': ("We go to the same school.", "我们去同一所学校。"),
    'much': ("How much is this book?", "这本书多少钱？"),
    'many': ("How many students are there?", "有多少名学生？"),
    'little': ("I have a little money.", "我有一点钱。"),
    'every': ("I go to school every day.", "我每天去上学。"),
    'right': ("You are right.", "你是对的。"),
    'wrong': ("What's wrong with you?", "你怎么了？"),
    'real': ("This is a real diamond.", "这是一颗真钻石。"),
    'true': ("His dream came true.", "他的梦想实现了。"),
    'full': ("The bus is full.", "公交车满了。"),
    'glad': ("I am glad to meet you.", "很高兴见到你。"),
    'sorry': ("I am sorry for being late.", "对不起，我迟到了。"),
    'sure': ("Are you sure about that?", "你确定吗？"),
    'clear': ("The water is clear.", "水很清澈。"),
    'clean': ("Please clean the room.", "请打扫房间。"),
    'dirty': ("My shoes are dirty.", "我的鞋脏了。"),
    'fast': ("He runs fast.", "他跑得快。"),
    'slow': ("The turtle is slow.", "乌龟很慢。"),
    'early': ("I get up early every day.", "我每天早起。"),
    'late': ("Don't be late for school.", "上学不要迟到。"),
    'far': ("How far is the station?", "车站有多远？"),
    'near': ("The school is near my home.", "学校在我家附近。"),
    'open': ("Please open the door.", "请开门。"),
    'close': ("Please close the window.", "请关窗。"),
    'begin': ("The class begins at eight.", "八点开始上课。"),
    'finish': ("I finish my homework at nine.", "我九点完成作业。"),
    'start': ("Let's start the game.", "我们开始游戏吧。"),
    'stop': ("Stop talking, please.", "请停止讲话。"),
    'keep': ("Please keep quiet.", "请保持安静。"),
    'help': ("Can you help me?", "你能帮我吗？"),
    'love': ("I love my family.", "我爱我的家人。"),
    'hate': ("I hate getting up early.", "我讨厌早起。"),
    'hope': ("I hope you can come.", "我希望你能来。"),
    'wish': ("I wish you good luck.", "祝你好运。"),
    'need': ("I need some help.", "我需要一些帮助。"),
    'find': ("I can't find my key.", "我找不到我的钥匙了。"),
    'call': ("I will call you tonight.", "我今晚给你打电话。"),
    'show': ("Show me your ticket.", "给我看看你的票。"),
    'ask': ("May I ask a question?", "我可以问一个问题吗？"),
    'answer': ("Please answer the question.", "请回答这个问题。"),
    'remember': ("Remember to lock the door.", "记得锁门。"),
    'forget': ("Don't forget to do your homework.", "别忘了做作业。"),
    'try': ("Please try your best.", "请尽力而为。"),
    'learn': ("I want to learn English well.", "我想学好英语。"),
    'teach': ("She teaches us English.", "她教我们英语。"),
    'study': ("I study hard for the exam.", "我为考试努力学习。"),
    'read': ("I like to read books.", "我喜欢读书。"),
    'write': ("Please write down your name.", "请写下你的名字。"),
    'listen': ("Listen to the teacher carefully.", "认真听老师讲课。"),
    'speak': ("She can speak English.", "她会说英语。"),
    'talk': ("They are talking about the movie.", "他们正在谈论那部电影。"),
    'walk': ("I walk to school every day.", "我每天走路去学校。"),
    'run': ("He runs very fast.", "他跑得很快。"),
    'swim': ("I go swimming every weekend.", "我每个周末去游泳。"),
    'sing': ("She sings a beautiful song.", "她唱了一首美丽的歌。"),
    'dance': ("They are dancing in the room.", "他们正在房间里跳舞。"),
    'draw': ("She likes to draw pictures.", "她喜欢画画。"),
    'buy': ("I want to buy a gift for my mother.", "我想给妈妈买份礼物。"),
    'sell': ("The shop sells fruits.", "这家店卖水果。"),
    'pay': ("I pay ten yuan for the book.", "我付了十元钱买这本书。"),
    'cost': ("The bag costs fifty yuan.", "这个包花费五十元。"),
    'spend': ("I spend two hours on homework.", "我花两个小时做作业。"),
    'bring': ("Please bring your book tomorrow.", "明天请带上你的书。"),
    'take': ("Please take this book to the library.", "请把这本书带到图书馆去。"),
    'carry': ("Let me carry the box for you.", "让我帮你搬这个箱子。"),
    'catch': ("I catch the bus every morning.", "我每天早上赶公交车。"),
    'drive': ("My father drives me to school.", "我爸爸开车送我去学校。"),
    'fly': ("We fly to Beijing for vacation.", "我们飞往北京度假。"),
    'grow': ("The flowers grow quickly in spring.", "花在春天长得很快。"),
    'live': ("I live in Shanghai.", "我住在上海。"),
    'die': ("Plants die without water.", "植物没有水会死。"),
    'feel': ("I feel happy today.", "我今天感到开心。"),
    'smell': ("The flowers smell sweet.", "这些花闻起来很香。"),
    'taste': ("The soup tastes good.", "汤尝起来很好。"),
    'sound': ("That sounds great!", "那听起来很棒！"),
    'look': ("You look beautiful today.", "你今天看起来很漂亮。"),
    'become': ("She becomes a teacher.", "她成为了一名老师。"),
    'leave': ("The train leaves at six.", "火车六点出发。"),
    'meet': ("Nice to meet you.", "很高兴见到你。"),
    'lose': ("I lost my keys.", "我丢了钥匙。"),
    'win': ("Our team won the game.", "我们队赢了比赛。"),
    'wear': ("She wears a red dress.", "她穿着一件红裙子。"),
    'put': ("Put on your coat. It's cold.", "穿上你的外套。天气冷。"),
    'cut': ("Please cut the cake.", "请切蛋糕。"),
    'push': ("Don't push the door. Pull it.", "别推门。拉它。"),
    'pull': ("The horse is pulling the cart.", "马正在拉车。"),
    'throw': ("Don't throw paper on the floor.", "不要把纸扔在地上。"),
    'turn': ("Turn left at the corner.", "在拐角处左转。"),
    'fall': ("Be careful not to fall.", "小心别摔倒。"),
    'stand': ("Please stand up.", "请起立。"),
    'sit': ("Please sit down.", "请坐下。"),
    'sleep': ("I sleep eight hours every night.", "我每晚睡八小时。"),
    'wake': ("I wake up at six every morning.", "我每天早上六点醒来。"),
    'wash': ("Please wash your hands before dinner.", "晚饭前请洗手。"),
    'cook': ("My mother cooks dinner every day.", "我妈妈每天做晚饭。"),
    'eat': ("We eat lunch at school.", "我们在学校吃午饭。"),
    'drink': ("I drink a lot of water every day.", "我每天喝很多水。"),
    'play': ("The children are playing in the park.", "孩子们在公园里玩。"),
    'game': ("We played a fun game yesterday.", "我们昨天玩了一个有趣的游戏。"),
    'sport': ("My favorite sport is basketball.", "我最喜欢的运动是篮球。"),
    'ball': ("The boy is playing with a ball.", "那个男孩在玩球。"),
    'team': ("He is on the school basketball team.", "他是学校篮球队的。"),
    'music': ("I like listening to music.", "我喜欢听音乐。"),
    'song': ("This song is very beautiful.", "这首歌很美。"),
    'movie': ("Let's watch a movie tonight.", "我们今晚看电影吧。"),
    'story': ("Grandma tells me a story every night.", "奶奶每晚给我讲一个故事。"),
    'picture': ("I took a picture of the flower.", "我给花拍了张照片。"),
    'computer': ("I use the computer to do homework.", "我用电脑做作业。"),
    'phone': ("My phone number is 123456.", "我的电话号码是123456。"),
    'city': ("Beijing is a big city.", "北京是一个大城市。"),
    'country': ("China is a great country.", "中国是一个伟大的国家。"),
    'world': ("I want to travel around the world.", "我想环游世界。"),
    'river': ("The river is very long.", "这条河很长。"),
    'mountain': ("We climbed the mountain last weekend.", "我们上周末爬了山。"),
    'sea': ("I like swimming in the sea.", "我喜欢在海里游泳。"),
    'sky': ("Birds fly in the sky.", "鸟在天空中飞翔。"),
    'sun': ("The sun rises in the east.", "太阳从东方升起。"),
    'moon': ("The moon is very bright tonight.", "今晚月亮很亮。"),
    'star': ("There are many stars in the sky.", "天空中有很多星星。"),
    'tree': ("There is a tall tree in front of the house.", "房子前面有一棵高树。"),
    'flower': ("These flowers are very beautiful.", "这些花很漂亮。"),
    'animal': ("I love animals very much.", "我非常喜欢动物。"),
    'dog': ("The dog is running in the park.", "狗正在公园里跑。"),
    'cat': ("My cat likes to sleep on the sofa.", "我的猫喜欢在沙发上睡觉。"),
    'bird': ("The bird can sing beautifully.", "这只鸟唱歌很好听。"),
    'fish': ("We went fishing by the river.", "我们去河边钓鱼了。"),
    'horse': ("The horse runs very fast.", "这匹马跑得很快。"),
    'body': ("We should keep our body healthy.", "我们应该保持身体健康。"),
    'head': ("She shook her head.", "她摇了摇头。"),
    'face': ("Her face is round.", "她的脸是圆的。"),
    'eye': ("She has big eyes.", "她有大眼睛。"),
    'ear': ("The rabbit has long ears.", "兔子有长耳朵。"),
    'nose': ("He has a big nose.", "他有一个大鼻子。"),
    'mouth': ("Open your mouth please.", "请张开你的嘴。"),
    'hand': ("She raised her hand.", "她举起了手。"),
    'foot': ("I go to school on foot.", "我步行去上学。"),
    'arm': ("She hurt her arm.", "她伤到了手臂。"),
    'leg': ("The table has four legs.", "桌子有四条腿。"),
    'hair': ("She has long black hair.", "她有长长的黑发。"),
    'heart': ("She has a kind heart.", "她有一颗善良的心。"),
    'health': ("Eating well is good for health.", "吃得好对健康有益。"),
    'doctor': ("The doctor helped the sick boy.", "医生帮助了那个生病的男孩。"),
    'nurse': ("The nurse is very kind.", "那位护士非常和蔼。"),
    'hospital': ("He was taken to the hospital.", "他被送到了医院。"),
    'medicine': ("Take this medicine three times a day.", "这药一天吃三次。"),
    'shop': ("There is a shop near my home.", "我家附近有一家商店。"),
    'market': ("My mother goes to the market every morning.", "我妈妈每天早上都去市场。"),
    'money': ("I save money to buy a bike.", "我攒钱买自行车。"),
    'price': ("The price of the book is fair.", "这本书的价格很合理。"),
    'cheap': ("This pen is cheap.", "这支钢笔很便宜。"),
    'expensive': ("The car is too expensive.", "这辆车太贵了。"),
    'free': ("I am free on Sunday.", "我星期天有空。"),
    'paper': ("Please give me a piece of paper.", "请给我一张纸。"),
    'letter': ("I wrote a letter to my friend.", "我给朋友写了一封信。"),
    'word': ("What does this word mean?", "这个词是什么意思？"),
    'name': ("My name is Li Ming.", "我的名字是李明。"),
    'number': ("What is your phone number?", "你的电话号码是多少？"),
    'question': ("Please answer my question.", "请回答我的问题。"),
    'idea': ("That's a good idea!", "那是个好主意！"),
    'example': ("Please give me an example.", "请给我举个例子。"),
    'place': ("This is a beautiful place.", "这是一个美丽的地方。"),
    'home': ("I go home at five.", "我五点回家。"),
    'family': ("There are four people in my family.", "我家有四口人。"),
    'person': ("She is a kind person.", "她是个善良的人。"),
    'thing': ("The most important thing is to study.", "最重要的事情是学习。"),
    'part': ("I took part in the sports meeting.", "我参加了运动会。"),
    'kind': ("She is a kind teacher.", "她是一位善良的老师。"),
    'lot': ("There are a lot of books in the library.", "图书馆有很多书。"),
    'enough': ("We have enough time.", "我们有足够的时间。"),
    'such': ("She is such a kind girl.", "她是如此善良的一个女孩。"),
    'still': ("He is still sleeping.", "他还在睡觉。"),
    'always': ("She always gets up early.", "她总是早起。"),
    'never': ("I never tell lies.", "我从不说谎。"),
    'often': ("We often play basketball after school.", "我们经常放学后打篮球。"),
    'usually': ("I usually go to bed at ten.", "我通常十点睡觉。"),
    'sometimes': ("I sometimes go to the library.", "我有时候去图书馆。"),
    'seldom': ("She seldom eats junk food.", "她很少吃垃圾食品。"),
    'already': ("I have already finished my homework.", "我已经做完作业了。"),
    'yet': ("Have you finished your homework yet?", "你做完作业了吗？"),
    'once': ("I have been to Beijing once.", "我去过一次北京。"),
    'since': ("I have studied English since 2020.", "我从2020年开始学英语。"),
    'ago': ("I met her two days ago.", "我两天前遇到了她。"),
    'before': ("Wash your hands before meals.", "饭前要洗手。"),
    'during': ("I read a book during the summer.", "我在夏天读了一本书。"),
    'until': ("I waited until she came back.", "我一直等到她回来。"),
    'while': ("I listened to music while doing homework.", "我做作业时听音乐。"),
    'although': ("Although it rained, we went out.", "虽然下雨了，我们还是出去了。"),
    'where': ("Where do you live?", "你住在哪里？"),
    'why': ("Why are you late?", "你为什么迟到？"),
    'whom': ("Whom did you see yesterday?", "你昨天看见了谁？"),
    'whose': ("Whose book is this?", "这是谁的书？"),
    'that': ("That is my seat.", "那是我的座位。"),
    'those': ("Those apples are red.", "那些苹果是红色的。"),
    'here': ("Here is your gift.", "这是你的礼物。"),
    'there': ("The park is over there.", "公园在那边。"),
    'everywhere': ("I looked for my key everywhere.", "我到处找我的钥匙。"),
    'somewhere': ("I put my book somewhere in the room.", "我把书放在房间的某个地方了。"),
    'anywhere': ("I can't find my pen anywhere.", "我到处都找不到我的钢笔。"),
    'everyone': ("Everyone in our class likes sports.", "我们班每个人都喜欢运动。"),
    'someone': ("Someone is waiting for you.", "有人在等你。"),
    'anyone': ("Does anyone know the answer?", "有人知道答案吗？"),
    'everything': ("Everything goes well.", "一切顺利。"),
    'something': ("I have something to tell you.", "我有些事情要告诉你。"),
    'nothing': ("There is nothing to worry about.", "没什么好担心的。"),
    'myself': ("I did my homework by myself.", "我自己做了作业。"),
    'yourself': ("Help yourself to some cake.", "请随便吃点蛋糕。"),
    'himself': ("He taught himself English.", "他自学了英语。"),
    'herself': ("She cut herself by accident.", "她不小心割到了自己。"),
    'itself': ("The door closed by itself.", "门自己关上了。"),
    'ourselves': ("We enjoyed ourselves at the party.", "我们在聚会上玩得很开心。"),
    'yourselves': ("You should take care of yourselves.", "你们应该照顾好自己。"),
    'themselves': ("They taught themselves to swim.", "他们自学了游泳。"),
    'Monday': ("I go to school on Monday.", "我星期一去上学。"),
    'Tuesday': ("She has a test on Tuesday.", "她星期二有个考试。"),
    'Wednesday': ("We play soccer on Wednesday.", "我们星期三踢足球。"),
    'Thursday': ("I have art class on Thursday.", "我星期四有美术课。"),
    'Friday': ("We clean our classroom every Friday.", "我们每个星期五打扫教室。"),
    'Saturday': ("I go to the park on Saturday.", "我星期六去公园。"),
    'Sunday': ("We stay at home on Sunday.", "我们星期天待在家里。"),
    'January': ("January is the first month of the year.", "一月是一年中的第一个月。"),
    'February': ("February is the shortest month.", "二月是最短的月份。"),
    'March': ("Spring begins in March.", "春天从三月开始。"),
    'April': ("April is warm and sunny.", "四月温暖晴朗。"),
    'May': ("May is my favorite month.", "五月是我最喜欢的月份。"),
    'June': ("School ends in June.", "学校六月放假。"),
    'July': ("July is very hot.", "七月很热。"),
    'August': ("We have a vacation in August.", "我们八月放假。"),
    'September': ("School starts in September.", "学校九月开学。"),
    'October': ("October is cool and nice.", "十月凉爽舒适。"),
    'November': ("November is the eleventh month.", "十一月是第十一个月。"),
    'December': ("Christmas is in December.", "圣诞节在十二月。"),
    'spring': ("Flowers bloom in spring.", "花在春天开放。"),
    'summer': ("I like swimming in summer.", "我喜欢在夏天游泳。"),
    'autumn': ("Leaves fall in autumn.", "秋天树叶落下。"),
    'winter': ("It snows in winter.", "冬天下雪。"),
    'weather': ("The weather is nice today.", "今天天气很好。"),
    'rain': ("It rains a lot in spring.", "春天雨水多。"),
    'snow': ("We can make a snowman when it snows.", "下雪时我们可以堆雪人。"),
    'wind': ("The wind is blowing strongly.", "风在猛烈地吹。"),
    'cloud': ("White clouds are in the sky.", "天空中有白云。"),
    'sunny': ("It is a sunny day.", "这是一个晴天。"),
    'subject': ("My favorite subject is English.", "我最喜欢的科目是英语。"),
    'Chinese': ("We study Chinese every day.", "我们每天学习语文。"),
    'English': ("I like speaking English.", "我喜欢说英语。"),
    'math': ("I am good at math.", "我擅长数学。"),
    'science': ("We have a science class today.", "我们今天有科学课。"),
    'history': ("I like reading history books.", "我喜欢读历史书。"),
    'geography': ("We study geography this term.", "这学期我们学习地理。"),
    'exam': ("We have an exam next week.", "我们下周有考试。"),
    'grade': ("She got good grades this term.", "这学期她取得了好成绩。"),
    'homework': ("I do my homework after school.", "我放学后做作业。"),
    'holiday': ("We have a holiday next week.", "我们下周放假。"),
    'breakfast': ("I have breakfast at seven.", "我七点吃早餐。"),
    'lunch': ("We have lunch at school.", "我们在学校吃午餐。"),
    'dinner': ("My family has dinner together.", "我们一家人一起吃晚餐。"),
    'kitchen': ("My mother is cooking in the kitchen.", "我妈妈正在厨房做饭。"),
    'bedroom': ("My bedroom is small but clean.", "我的卧室虽小但干净。"),
    'library': ("I read books in the library.", "我在图书馆看书。"),
    'restaurant': ("We ate dinner at a restaurant.", "我们在一家餐厅吃了晚餐。"),
    'supermarket': ("We go to the supermarket on weekends.", "我们周末去超市。"),
    'airport': ("We will meet you at the airport.", "我们会在机场接你。"),
    'station': ("The train station is far from here.", "火车站离这里很远。"),
    'bridge': ("We walked across the bridge.", "我们走过了那座桥。"),
    'street': ("Be careful when crossing the street.", "过马路时要小心。"),
    'farm': ("My uncle works on a farm.", "我叔叔在农场工作。"),
    'village': ("My grandmother lives in a small village.", "我奶奶住在一个小村庄。"),
    'factory': ("My father works in a factory.", "我爸爸在工厂工作。"),
    'bank': ("I put my money in the bank.", "我把钱存在银行。"),
    'hotel': ("We stayed at a hotel during the trip.", "旅行期间我们住在一家酒店。"),
    'police': ("The police helped the lost child.", "警察帮助了走失的孩子。"),
    'travel': ("I want to travel all over China.", "我想游遍全中国。"),
    'trip': ("We had a wonderful trip to the beach.", "我们去海滩的旅行很愉快。"),
    'visit': ("We visited my grandparents last weekend.", "我们上周末去看望了爷爷奶奶。"),
    'arrive': ("We arrived at the station on time.", "我们准时到达了车站。"),
    'follow': ("Follow me, please.", "请跟我来。"),
    'change': ("I need to change my clothes.", "我需要换衣服。"),
    'improve': ("I want to improve my English.", "我想提高我的英语。"),
    'protect': ("We should protect the environment.", "我们应该保护环境。"),
    'save': ("Please save water.", "请节约用水。"),
    'collect': ("I like collecting stamps.", "我喜欢集邮。"),
    'choose': ("Which one do you choose?", "你选哪个？"),
    'decide': ("I decided to study harder.", "我决定更加努力学习。"),
    'plan': ("I plan to visit Beijing next year.", "我计划明年去北京。"),
    'prepare': ("I am preparing for the exam.", "我正在为考试做准备。"),
    'worry': ("Don't worry about the test.", "别担心考试。"),
    'exercise': ("I do exercise every morning.", "我每天早上锻炼。"),
    'practice': ("Practice makes perfect.", "熟能生巧。"),
    'pass': ("I passed the exam.", "我通过了考试。"),
    'borrow': ("Can I borrow your pen?", "我可以借你的钢笔吗？"),
    'lend': ("Can you lend me your bike?", "你能把自行车借给我吗？"),
    'return': ("Please return the book on time.", "请按时还书。"),
    'welcome': ("Welcome to our school.", "欢迎来到我们学校。"),
    'invite': ("I invited her to my birthday party.", "我邀请她来我的生日派对。"),
    'join': ("I want to join the art club.", "我想加入美术社团。"),
    'share': ("Let's share the cake.", "我们分享蛋糕吧。"),
    'discuss': ("We discussed the problem in class.", "我们在课堂上讨论了这个问题。"),
    'agree': ("I agree with you.", "我同意你的看法。"),
    'refuse': ("He refused to help me.", "他拒绝帮助我。"),
    'accept': ("I accepted his invitation.", "我接受了他的邀请。"),
    'believe': ("I believe you can do it.", "我相信你能做到。"),
    'encourage': ("My teacher encouraged me to try again.", "我的老师鼓励我再试一次。"),
    'support': ("My family supports me.", "我的家人支持我。"),
    'respect': ("We should respect our teachers.", "我们应该尊重老师。"),
    'wonder': ("I wonder what will happen.", "我想知道会发生什么。"),
    'matter': ("What's the matter with you?", "你怎么了？"),
    'danger': ("He is in danger.", "他正处于危险中。"),
    'safe': ("Keep your money in a safe place.", "把钱放在安全的地方。"),
    'peace': ("We live in peace.", "我们生活在和平中。"),
    'nature': ("I love being close to nature.", "我喜欢亲近自然。"),
    'pollution': ("Air pollution is a serious problem.", "空气污染是一个严重的问题。"),
    'meaning': ("What is the meaning of this word?", "这个词是什么意思？"),
    'secret': ("Can you keep a secret?", "你能保密吗？"),
    'truth': ("Always tell the truth.", "永远说实话。"),
    'habit': ("Reading is a good habit.", "读书是一个好习惯。"),
    'talent': ("She has a talent for music.", "她有音乐天赋。"),
    'skill': ("Writing is an important skill.", "写作是一项重要的技能。"),
    'experience': ("I have experience in teaching.", "我有教学经验。"),
    'knowledge': ("Knowledge is power.", "知识就是力量。"),
    'success': ("Hard work leads to success.", "努力带来成功。"),
    'failure': ("Failure is the mother of success.", "失败是成功之母。"),
    'progress': ("I made great progress in English.", "我在英语上取得了很大进步。"),
    'result': ("The result of the game was surprising.", "比赛结果令人惊讶。"),
    'reason': ("The reason for his absence was illness.", "他缺席的原因是生病了。"),
    'purpose': ("What is the purpose of this lesson?", "这节课的目的是什么？"),
}

# ===== Senior word examples (lines 512-981, ~200 words) =====
senior_examples = {
    'abandon': ("He had to abandon the project.", "他不得不放弃这个项目。"),
    'ability': ("She has the ability to solve the problem.", "她有解决这个问题的能力。"),
    'abroad': ("She wants to study abroad.", "她想出国留学。"),
    'absence': ("His absence made the teacher worried.", "他的缺席让老师很担心。"),
    'absolute': ("I have absolute trust in her.", "我绝对信任她。"),
    'absorb': ("He was absorbed in reading the book.", "他全神贯注地读书。"),
    'abstract': ("This idea is too abstract to understand.", "这个想法太抽象了，难以理解。"),
    'abundant': ("This area is abundant in natural resources.", "这个地区自然资源丰富。"),
    'academic': ("His academic performance is excellent.", "他的学业成绩很优秀。"),
    'accelerate': ("The car accelerated quickly.", "汽车迅速加速了。"),
    'access': ("Students have access to the library.", "学生可以使用图书馆。"),
    'accompany': ("I accompanied my mother to the hospital.", "我陪妈妈去了医院。"),
    'accomplish': ("He accomplished his goal in the end.", "他最终实现了他的目标。"),
    'accurate': ("Please give an accurate answer.", "请给出一个准确的答案。"),
    'accuse': ("She accused him of lying.", "她指责他撒谎。"),
    'achieve': ("She achieved her dream of becoming a doctor.", "她实现了成为医生的梦想。"),
    'acknowledge': ("He acknowledged his mistake.", "他承认了自己的错误。"),
    'acquire': ("She acquired a lot of knowledge in school.", "她在学校学到了很多知识。"),
    'adapt': ("He adapted quickly to the new environment.", "他很快适应了新环境。"),
    'adequate': ("The supply is adequate for the trip.", "补给足够这次旅行了。"),
    'adjust': ("You need to adjust to the new rules.", "你需要适应新规则。"),
    'admire': ("I admire her for her courage.", "我钦佩她的勇气。"),
    'admit': ("He admitted breaking the window.", "他承认打破了窗户。"),
    'adopt': ("They adopted a child from the orphanage.", "他们从孤儿院收养了一个孩子。"),
    'advance': ("Science and technology continue to advance.", "科学技术不断进步。"),
    'advantage': ("Being tall is an advantage in basketball.", "个子高是打篮球的优势。"),
    'advertise': ("The company advertised for new workers.", "这家公司登广告招聘新工人。"),
    'affair': ("He is busy with family affairs.", "他忙于家庭事务。"),
    'affect': ("The weather affects my mood.", "天气影响我的心情。"),
    'afford': ("I can't afford to buy the car.", "我买不起这辆车。"),
    'aggressive': ("He has an aggressive playing style.", "他有一种进攻性的打球风格。"),
    'agriculture': ("Agriculture is the foundation of the country.", "农业是国家的基石。"),
    'allocate': ("The school allocated money for new books.", "学校拨了款买新书。"),
    'allow': ("My parents allow me to watch TV on weekends.", "我父母允许我周末看电视。"),
    'alternative': ("We need to find an alternative solution.", "我们需要找到替代方案。"),
    'amaze': ("Her performance amazed everyone.", "她的表演让所有人惊叹。"),
    'ambition': ("His ambition is to become a scientist.", "他的志向是成为科学家。"),
    'analyse': ("We need to analyse the data carefully.", "我们需要仔细分析数据。"),
    'ancestor': ("My ancestors came from the south.", "我的祖先来自南方。"),
    'announce': ("The teacher announced the exam results.", "老师宣布了考试成绩。"),
    'annual': ("The school holds an annual sports day.", "学校每年举办运动会。"),
    'anxiety': ("She felt anxiety before the exam.", "考试前她感到焦虑。"),
    'apparent': ("It is apparent that he is lying.", "很明显他在说谎。"),
    'appeal': ("The idea of traveling appeals to me.", "旅行的想法吸引了我。"),
    'appetite': ("I have a good appetite today.", "我今天胃口很好。"),
    'applaud': ("The audience applauded loudly.", "观众热烈鼓掌。"),
    'apply': ("I applied for a part-time job.", "我申请了一份兼职工作。"),
    'appoint': ("She was appointed as the team leader.", "她被任命为队长。"),
    'appreciate': ("I appreciate your help very much.", "我非常感激你的帮助。"),
    'approach': ("We need a new approach to this problem.", "我们需要一个新方法来解决这个问题。"),
    'appropriate': ("This dress is appropriate for the party.", "这件裙子适合在派对上穿。"),
    'approve': ("My parents approved of my decision.", "我父母同意了我的决定。"),
    'argue': ("Don't argue with your parents.", "不要和父母争吵。"),
    'arrange': ("I arranged a meeting for tomorrow.", "我安排了一个明天会议。"),
    'artificial': ("The flowers are artificial.", "这些花是假的。"),
    'aspect': ("We should consider every aspect of the plan.", "我们应该考虑计划的各个方面。"),
    'assemble': ("All students assembled in the hall.", "所有学生都在大厅集合了。"),
    'assess': ("The teacher assessed our performance.", "老师评估了我们的表现。"),
    'assign': ("The teacher assigned homework for the weekend.", "老师布置了周末作业。"),
    'assist': ("She assisted the old man across the street.", "她帮助老人过马路。"),
    'associate': ("I associate summer with swimming.", "我把夏天和游泳联系起来。"),
    'assume': ("I assume you know the truth.", "我假设你知道真相。"),
    'atmosphere': ("The atmosphere in the room was warm.", "房间里的氛围很温暖。"),
    'attach': ("Please attach the photo to the form.", "请把照片附在表格上。"),
    'attempt': ("I will attempt to solve this problem.", "我会尝试解决这个问题。"),
    'attend': ("All students must attend the meeting.", "所有学生都必须参加会议。"),
    'attitude': ("She has a positive attitude towards life.", "她对生活有积极的态度。"),
    'attract': ("The bright colors attract butterflies.", "鲜艳的颜色吸引蝴蝶。"),
    'authority': ("The local authorities are responsible for safety.", "地方当局负责安全。"),
    'available': ("Is this seat available?", "这个座位有人吗？"),
    'average': ("His grades are above average.", "他的成绩高于平均水平。"),
    'avoid': ("You should avoid eating too much sugar.", "你应该避免吃太多糖。"),
    'aware': ("She was not aware of the danger.", "她没有意识到危险。"),
    'balance': ("You need to keep a balance between study and rest.", "你需要保持学习和休息的平衡。"),
    'barrier': ("Language can be a barrier to communication.", "语言可能是沟通的障碍。"),
    'behalf': ("I am writing on behalf of my class.", "我代表我的班级写这封信。"),
    'behave': ("Please behave well in class.", "请在课堂上表现好。"),
    'belief': ("It is my belief that hard work pays off.", "我相信努力会有回报。"),
    'belong': ("This book belongs to the library.", "这本书属于图书馆。"),
    'benefit': ("Exercise benefits our health.", "锻炼对我们的健康有益。"),
    'betray': ("He felt betrayed by his best friend.", "他感到被他最好的朋友背叛了。"),
    'bother': ("Don't bother me while I am studying.", "我学习时别打扰我。"),
    'boundary': ("The river forms the boundary between the two countries.", "这条河形成了两国之间的边界。"),
    'brilliant': ("She has a brilliant idea.", "她有一个绝妙的主意。"),
    'budget': ("We need to stay within our budget.", "我们需要控制在预算内。"),
    'burden': ("He doesn't want to be a burden to his family.", "他不想成为家里的负担。"),
    'calculate': ("Can you calculate the total cost?", "你能计算总费用吗？"),
    'campaign': ("They launched a campaign to clean the park.", "他们发起了一场清洁公园的运动。"),
    'capable': ("She is capable of finishing the task alone.", "她能独自完成这项任务。"),
    'capacity': ("The hall has a capacity of 500 people.", "这个大厅能容纳500人。"),
    'capture': ("The photo captured a beautiful moment.", "这张照片捕捉到了一个美丽的瞬间。"),
    'career': ("She chose teaching as her career.", "她选择了教书作为职业。"),
    'cast': ("They cast their votes for the new leader.", "他们投票选出了新领导。"),
    'category': ("Books are put into different categories.", "书被分成不同的类别。"),
    'cause': ("Smoking can cause many diseases.", "吸烟可能导致很多疾病。"),
    'celebrate': ("We celebrate Christmas with our family.", "我们和家人一起庆祝圣诞节。"),
    'ceremony': ("We attended the opening ceremony of the school.", "我们参加了学校的开学典礼。"),
    'challenge': ("Learning a new language is a big challenge.", "学一门新语言是一个大挑战。"),
    'character': ("She has a strong character.", "她有坚强的性格。"),
    'charity': ("We gave money to charity.", "我们捐钱给慈善机构。"),
    'chemical': ("We studied chemical reactions in science class.", "我们在科学课上学习了化学反应。"),
    'circumstance': ("Under no circumstances should you give up.", "在任何情况下你都不该放弃。"),
    'citizen': ("He is a good citizen of this country.", "他是这个国家的好公民。"),
    'civilization': ("Ancient China had a great civilization.", "古代中国有伟大的文明。"),
    'claim': ("He claimed that he saw the accident.", "他声称他目睹了事故。"),
    'classify': ("Books are classified by subject.", "书按科目分类。"),
    'climate': ("The climate here is warm and wet.", "这里的气候温暖潮湿。"),
    'coach': ("The coach taught us how to play basketball.", "教练教我们如何打篮球。"),
    'collapse': ("The old building collapsed after the earthquake.", "旧楼在地震后倒塌了。"),
    'colleague': ("She gets along well with her colleagues.", "她和同事相处得很好。"),
    'combine': ("We should combine theory with practice.", "我们应该把理论和实践结合起来。"),
    'command': ("He has a good command of English.", "他英语掌握得很好。"),
    'comment': ("Please comment on my article.", "请评论一下我的文章。"),
    'commit': ("He committed a serious crime.", "他犯下了严重的罪行。"),
    'communicate': ("We communicate with each other by email.", "我们通过电子邮件互相交流。"),
    'community': ("We should serve the community.", "我们应该服务社区。"),
    'companion': ("My dog is my faithful companion.", "我的狗是我忠实的伙伴。"),
    'compare': ("Don't compare yourself with others.", "不要拿自己和别人比较。"),
    'compete': ("She competed with ten other runners.", "她和其他十名选手比赛。"),
    'complain': ("He often complains about the food.", "他经常抱怨食物。"),
    'complete': ("I need to complete the project by Friday.", "我需要在周五前完成这个项目。"),
    'complex': ("This math problem is too complex.", "这道数学题太复杂了。"),
    'component': ("Engine is a key component of a car.", "发动机是汽车的关键部件。"),
    'concentrate': ("I need to concentrate on my studies.", "我需要专注于学习。"),
    'concept': ("This is a difficult concept to understand.", "这是一个难以理解的概念。"),
    'concern': ("I am concerned about your health.", "我担心你的健康。"),
    'conclude': ("What can you conclude from the experiment?", "你从实验中能得出什么结论？"),
    'condition': ("You can join on condition that you follow the rules.", "你可以加入，条件是你遵守规则。"),
    'conduct': ("The scientist conducted an experiment.", "科学家进行了一项实验。"),
    'conference': ("She attended an international conference.", "她参加了一个国际会议。"),
    'confess': ("He confessed to stealing the money.", "他承认偷了钱。"),
    'confident': ("I am confident that I will pass the exam.", "我有信心通过考试。"),
    'confirm': ("Please confirm your attendance.", "请确认你是否参加。"),
    'conflict': ("The two countries are in conflict over the land.", "这两个国家在土地上发生了冲突。"),
    'confuse': ("I often confuse the twins.", "我经常把这对双胞胎搞混。"),
    'connect': ("This road connects the two cities.", "这条路连接两座城市。"),
    'conquer': ("She conquered her fear of public speaking.", "她克服了对公开演讲的恐惧。"),
    'conscience': ("I have a clear conscience.", "我问心无愧。"),
    'conscious': ("He was conscious of his mistake.", "他意识到了自己的错误。"),
    'consequence': ("He had to face the consequences of his actions.", "他不得不面对自己行为的后果。"),
    'conservative': ("My parents are conservative about new ideas.", "我的父母对新想法很保守。"),
    'consider': ("Please consider my suggestion.", "请考虑我的建议。"),
    'consistent': ("His actions are consistent with his words.", "他言行一致。"),
    'constant': ("She is in constant pain.", "她一直处于疼痛中。"),
    'construct': ("They are constructing a new bridge.", "他们正在建造一座新桥。"),
    'consult': ("You should consult a doctor if you feel sick.", "如果你感觉不舒服，应该咨询医生。"),
    'consume': ("This car consumes a lot of fuel.", "这辆车很耗油。"),
    'contain': ("This box contains my toys.", "这个盒子里有我的玩具。"),
    'contemporary': ("I like contemporary art.", "我喜欢当代艺术。"),
    'content': ("He is content with his life.", "他对自己的生活很满足。"),
    'contest': ("She won first place in the singing contest.", "她在歌唱比赛中得了第一名。"),
    'continent': ("Africa is a large continent.", "非洲是一个大洲。"),
    'contribute': ("Everyone should contribute to the team.", "每个人都应该为团队做贡献。"),
    'convenient': ("It is convenient to take the subway.", "坐地铁很方便。"),
    'convince': ("I convinced her to join our club.", "我说服她加入了我们的俱乐部。"),
    'cooperate': ("We need to cooperate with each other.", "我们需要互相合作。"),
    'cope': ("She learned to cope with stress.", "她学会了应对压力。"),
    'core': ("Honesty is at the core of his character.", "诚实是他性格的核心。"),
    'corporate': ("He works for a big corporate company.", "他在一家大公司工作。"),
    'correct': ("Your answer is correct.", "你的答案是正确的。"),
    'correspond': ("His actions don't correspond with his words.", "他的言行不一致。"),
    'council': ("The city council made a new decision.", "市议会做出了新的决定。"),
    'courage': ("She had the courage to speak up.", "她有勇气站出来说话。"),
    'crash': ("The two cars crashed into each other.", "两辆车撞在了一起。"),
    'create': ("The artist created a beautiful painting.", "艺术家创作了一幅美丽的画。"),
    'creature': ("Dogs are friendly creatures.", "狗是友好的生物。"),
    'crime': ("It is a crime to steal.", "偷盗是犯罪。"),
    'crisis': ("Every crisis also brings opportunities.", "每一次危机也带来机会。"),
    'criterion': ("What is the criterion for success?", "成功的标准是什么？"),
    'critical': ("Critical thinking is important for students.", "批判性思维对学生很重要。"),
    'cultivate': ("He cultivated the habit of reading.", "他培养了读书的习惯。"),
    'curious': ("I am curious about the world.", "我对世界很好奇。"),
    'current': ("What is the current situation?", "目前的情况怎么样？"),
    'custom': ("It is a custom to give gifts at Christmas.", "圣诞节送礼是一个习俗。"),
    'cycle': ("The water cycle is a natural process.", "水循环是一个自然过程。"),
    'damage': ("The storm caused great damage.", "暴风雨造成了巨大的破坏。"),
    'debate': ("The students had a debate about the topic.", "学生们就这个话题进行了辩论。"),
    'debt': ("He is in debt because of the loan.", "他因为贷款而负债。"),
    'decade': ("The city has changed a lot over the past decade.", "过去十年这座城市变化很大。"),
    'decline': ("The population of the village is in decline.", "这个村庄的人口在减少。"),
    'decorate': ("We decorated the room for the party.", "我们为派对装饰了房间。"),
    'decrease': ("The number of students decreased this year.", "今年学生人数减少了。"),
    'defeat': ("Our team defeated the opponent.", "我们的队伍击败了对手。"),
    'defend': ("The soldiers defended the country.", "士兵们保卫了国家。"),
    'define': ("Can you define this word?", "你能定义这个词吗？"),
    'definite': ("I need a definite answer.", "我需要一个明确的答案。"),
    'degree': ("To some degree, I agree with you.", "在某种程度上，我同意你的看法。"),
    'delay': ("The flight was delayed due to bad weather.", "由于天气不好，航班延误了。"),
    'deliberate': ("It was a deliberate lie.", "那是一个故意的谎言。"),
    'delicate': ("The china cup is very delicate.", "这个瓷杯很精致。"),
    'deliver': ("The postman delivers letters every day.", "邮递员每天送信。"),
    'demand': ("There is a high demand for skilled workers.", "对技术工人的需求很大。"),
    'demonstrate': ("The teacher demonstrated the experiment.", "老师示范了实验。"),
    'depart': ("The train departs at six o'clock.", "火车六点出发。"),
    'depend': ("The price depends on the quality.", "价格取决于质量。"),
    'deposit': ("I deposited money in the bank.", "我把钱存进了银行。"),
    'depress': ("The bad news depressed her.", "坏消息让她很沮丧。"),
    'derive': ("This word derives from Latin.", "这个词源于拉丁语。"),
    'deserve': ("She deserves a reward for her hard work.", "她努力工作，应得奖励。"),
    'desperate': ("He was desperate for water after the long walk.", "长途跋涉后他极度渴望水。"),
    'determine': ("We determined to finish the work on time.", "我们决定按时完成工作。"),
    'devote': ("She devoted herself to teaching.", "她致力于教学。"),
    'distinguish': ("Can you distinguish between the two colors?", "你能区分这两种颜色吗？"),
    'distribute': ("The teacher distributed the test papers.", "老师分发了试卷。"),
    'diverse': ("China has a diverse culture.", "中国有多元的文化。"),
    'domestic': ("The domestic flight takes two hours.", "国内航班需要两小时。"),
    'dominate': ("He dominated the game from the start.", "他从一开始就主导了比赛。"),
    'dramatic': ("There has been a dramatic change in the weather.", "天气发生了巨大的变化。"),
    'dynamic': ("She is a dynamic and energetic person.", "她是一个充满活力的动态的人。"),
    'eliminate': ("We need to eliminate poverty.", "我们需要消除贫困。"),
    'emerge': ("The sun emerged from behind the clouds.", "太阳从云层后面出来了。"),
    'emergency': ("In case of an emergency, call 120.", "紧急情况下，请拨打120。"),
    'emotion': ("She couldn't control her emotions.", "她控制不住自己的情绪。"),
    'emphasize': ("The teacher emphasized the importance of reading.", "老师强调了阅读的重要性。"),
    'enable': ("The scholarship enabled her to go to college.", "奖学金使她能够上大学。"),
    'encounter': ("I encountered many difficulties during the trip.", "旅行中我遇到了很多困难。"),
    'engage': ("She engaged in a conversation with him.", "她和他进行了交谈。"),
    'enormous': ("There is an enormous difference between the two.", "两者之间有巨大的差异。"),
    'enterprise': ("He runs a successful enterprise.", "他经营着一家成功的企业。"),
    'enthusiasm': ("She shows great enthusiasm for music.", "她对音乐表现出极大的热情。"),
    'equivalent': ("One dollar is equivalent to about seven yuan.", "一美元大约相当于七元人民币。"),
    'essential': ("Water is essential for life.", "水对生命来说是必要的。"),
    'evaluate': ("We need to evaluate the situation first.", "我们首先需要评估情况。"),
    'evidence': ("There is no evidence to support his claim.", "没有证据支持他的说法。"),
    'evolve': ("Species evolve over time.", "物种随着时间进化。"),
    'exaggerate': ("Don't exaggerate the problem.", "不要夸大问题。"),
    'examine': ("The doctor examined the patient carefully.", "医生仔细检查了病人。"),
    'exceed': ("The cost exceeded our budget.", "费用超出了我们的预算。"),
    'exception': ("Everyone passed the exam, with no exception.", "每个人都通过了考试，没有例外。"),
    'exchange': ("We exchanged gifts at the party.", "我们在聚会上交换了礼物。"),
    'exclude': ("The price excludes tax.", "这个价格不含税。"),
    'execute': ("We need to execute the plan as soon as possible.", "我们需要尽快执行计划。"),
    'exhibit': ("The museum exhibits many ancient artifacts.", "博物馆展出了许多古代文物。"),
    'expand': ("The company plans to expand its business.", "公司计划扩展业务。"),
    'explore': ("We explored the forest near our school.", "我们探索了学校附近的森林。"),
    'explosion': ("There was a loud explosion in the factory.", "工厂里发生了一声巨大的爆炸。"),
    'expose': ("Don't expose your skin to the sun for too long.", "不要让你的皮肤在太阳下暴露太久。"),
    'extend': ("We extended our stay for another day.", "我们把停留时间延长了一天。"),
    'extreme': ("The weather is extreme in this area.", "这个地区的天气很极端。"),
    'facility': ("The school has excellent sports facilities.", "学校有极好的体育设施。"),
    'factor': ("Hard work is the key factor in his success.", "努力是他成功的关键因素。"),
    'familiar': ("I am familiar with this street.", "我对这条街很熟悉。"),
    'fascinating': ("The documentary was fascinating.", "这部纪录片很吸引人。"),
    'flexible': ("We need to be flexible in our thinking.", "我们的思维需要灵活。"),
    'forecast': ("The weather forecast says it will rain.", "天气预报说会下雨。"),
    'fortune': ("He made a fortune in the oil business.", "他通过石油生意赚了一大笔钱。"),
    'frequent': ("There are frequent buses to the city center.", "有频繁的公交车去市中心。"),
    'genuine': ("This is a genuine diamond.", "这是一颗真钻石。"),
    'global': ("Global warming is a serious issue.", "全球变暖是一个严重的问题。"),
    'gradual': ("There has been a gradual improvement in his health.", "他的健康状况在逐渐改善。"),
    'guarantee': ("Hard work does not guarantee success.", "努力并不保证成功。"),
    'harmony': ("We live in harmony with nature.", "我们与自然和谐相处。"),
    'hesitate': ("Don't hesitate to ask for help.", "不要犹豫，尽管求助。"),
    'highlight': ("The report highlights the main problems.", "报告突出了主要问题。"),
    'horizon': ("Traveling can broaden your horizons.", "旅行可以开阔你的眼界。"),
    'ideal': ("This is the ideal place for a picnic.", "这是野餐的理想地点。"),
    'identify': ("I identified the man in the photo.", "我认出了照片中的那个人。"),
    'ignore': ("He ignored my advice.", "他无视了我的建议。"),
    'illustrate': ("The teacher illustrated the point with examples.", "老师用例子说明了这一点。"),
    'immigrant': ("The city has many immigrants from different countries.", "这个城市有很多来自不同国家的移民。"),
    'impact': ("The new law has a big impact on society.", "新法律对社会有很大的影响。"),
    'implement': ("We need to implement the new system.", "我们需要实施新系统。"),
    'imply': ("What are you implying?", "你在暗示什么？"),
    'impose': ("Don't impose your ideas on others.", "不要把你的想法强加给别人。"),
    'incredible': ("The view from the mountain was incredible.", "山上的景色令人难以置信。"),
    'independent': ("She is very independent for her age.", "以她的年龄来说，她非常独立。"),
    'indicate': ("The sign indicates the way to the station.", "指示牌指出了去车站的路。"),
    'individual': ("Each individual has their own talents.", "每个人都有他们自己的天赋。"),
    'influence': ("My parents have a great influence on me.", "我的父母对我有很大的影响。"),
    'inform': ("Please inform me of any changes.", "如有任何变化请通知我。"),
    'initial': ("My initial reaction was surprise.", "我最初的反应是惊讶。"),
    'initiative': ("She took the initiative to help others.", "她主动帮助别人。"),
    'injury': ("He suffered a serious injury in the accident.", "他在事故中受了重伤。"),
    'innocent': ("He was declared innocent of the crime.", "他被宣告无罪。"),
    'inspire': ("His story inspired me to work harder.", "他的故事激励我更加努力。"),
    'institution': ("Schools are important institutions in society.", "学校是社会的重要机构。"),
    'instrument': ("She plays several musical instruments.", "她会演奏好几种乐器。"),
    'insurance': ("You should buy health insurance.", "你应该买健康保险。"),
    'intellectual': ("Reading helps intellectual development.", "阅读有助于智力发展。"),
    'intelligent': ("She is an intelligent student.", "她是一个聪明的学生。"),
    'interfere': ("Don't interfere with my work.", "不要干扰我的工作。"),
    'interpret': ("I need to interpret what he said.", "我需要解释他说的话。"),
    'investigate': ("The police are investigating the case.", "警方正在调查这个案件。"),
    'involve': ("This project involves a lot of hard work.", "这个项目需要很多努力。"),
    'isolate': ("The village is isolated from the outside world.", "这个村庄与外界隔绝。"),
    'journal': ("She keeps a daily journal.", "她每天写日记。"),
    'judge': ("Don't judge a book by its cover.", "不要以貌取人。"),
    'justify': ("How can you justify your behavior?", "你怎么为你的行为辩护？"),
    'keen': ("She is keen on learning new things.", "她热衷于学习新事物。"),
    'launch': ("The company launched a new product.", "公司发布了一款新产品。"),
    'leak': ("The pipe is leaking water.", "水管在漏水。"),
    'legal': ("It is legal to drive at age 18.", "18岁开车是合法的。"),
    'liberal': ("She has liberal views on education.", "她对教育有开放的观点。"),
    'likely': ("It is likely to rain tomorrow.", "明天可能会下雨。"),
    'literary': ("He is interested in literary works.", "他对文学作品感兴趣。"),
    'logic': ("Your argument lacks logic.", "你的论点缺乏逻辑。"),
    'maintain': ("We should maintain good health.", "我们应该保持健康。"),
    'manufacture': ("This factory manufactures cars.", "这家工厂制造汽车。"),
    'measure': ("We need to take measures to protect the environment.", "我们需要采取措施保护环境。"),
    'mental': ("Physical exercise is good for mental health.", "体育锻炼对心理健康有益。"),
    'minority': ("Only a minority of students failed the exam.", "只有少数学生考试不及格。"),
    'modify': ("We need to modify the plan.", "我们需要修改计划。"),
    'monitor': ("The teacher monitors the students during the exam.", "老师在考试期间监考。"),
    'moral': ("The story teaches a moral lesson.", "这个故事有道德寓意。"),
    'motivate': ("Good teachers motivate their students.", "好老师激励他们的学生。"),
    'negotiate': ("They are negotiating a new contract.", "他们正在谈判一份新合同。"),
    'network': ("We have a network of friends all over the world.", "我们有一个遍布全世界的朋友网络。"),
    'nevertheless': ("It was raining; nevertheless, we went out.", "天下雨了；不过我们还是出去了。"),
    'normal': ("It is normal to feel nervous before an exam.", "考试前感到紧张是正常的。"),
    'numerous': ("I have told you numerous times.", "我跟你说过无数次了。"),
    'obey': ("Everyone should obey the traffic rules.", "每个人都应该遵守交通规则。"),
    'obstacle': ("Lack of money is the biggest obstacle.", "缺钱是最大的障碍。"),
    'obvious': ("It is obvious that he is lying.", "很明显他在说谎。"),
    'occasion': ("We met on several occasions.", "我们在几个场合见过面。"),
    'occupy': ("The table occupies too much space.", "这张桌子占了太多空间。"),
    'offend': ("I didn't mean to offend you.", "我不是有意冒犯你。"),
    'oppose': ("Many people oppose the new law.", "很多人反对新法律。"),
    'organize': ("She organized a party for her birthday.", "她为生日组织了一个派对。"),
    'original': ("This is the original painting.", "这是原作。"),
    'outcome': ("The outcome of the game was surprising.", "比赛的结果令人惊讶。"),
    'overcome': ("She overcame many difficulties.", "她克服了很多困难。"),
    'participate': ("I participated in the school sports meet.", "我参加了学校运动会。"),
    'particular': ("I have nothing particular to say.", "我没什么特别要说的。"),
    'passion': ("She has a passion for music.", "她对音乐充满热情。"),
    'patience': ("You need patience to learn a language.", "学习语言需要耐心。"),
    'perceive': ("I perceived a change in his attitude.", "我察觉到他态度的变化。"),
    'perform': ("She performed well in the exam.", "她在考试中表现出色。"),
    'permanent': ("I am looking for a permanent job.", "我在找一份固定工作。"),
    'permit': ("Smoking is not permitted in the hospital.", "医院里不允许吸烟。"),
    'persist': ("If you persist, you will succeed.", "如果你坚持下去，你会成功的。"),
    'personality': ("She has a charming personality.", "她有迷人的个性。"),
    'perspective': ("From my perspective, this is a good idea.", "从我的角度看，这是个好主意。"),
    'phenomenon': ("The northern lights are a natural phenomenon.", "北极光是一种自然现象。"),
    'philosophy': ("She studied philosophy at university.", "她在大学学习哲学。"),
    'physical': ("Regular physical exercise is important.", "定期体育锻炼很重要。"),
    'policy': ("The school has a strict policy on cheating.", "学校对作弊有严格的政策。"),
    'possess': ("She possesses great talent for music.", "她拥有极大的音乐天赋。"),
    'potential': ("Every student has the potential to succeed.", "每个学生都有成功的潜力。"),
    'poverty': ("Many people live in poverty in that area.", "那个地区很多人生活在贫困中。"),
    'precious': ("Time is precious.", "时间是宝贵的。"),
    'precise': ("We need precise measurements.", "我们需要精确的测量。"),
    'predict': ("It is hard to predict the future.", "很难预测未来。"),
    'prejudice': ("We should not have prejudice against others.", "我们不应该对别人有偏见。"),
    'preserve': ("We need to preserve the environment.", "我们需要保护环境。"),
    'pressure': ("She is under a lot of pressure from her parents.", "她承受着来自父母的很大压力。"),
    'previous': ("I have previous experience in this job.", "我以前做过这份工作。"),
    'principle': ("She sticks to her principles.", "她坚持自己的原则。"),
    'privilege': ("It is a privilege to meet you.", "见到你很荣幸。"),
    'procedure': ("Follow the safety procedure carefully.", "仔细遵守安全程序。"),
    'profession': ("Teaching is a noble profession.", "教书是一个高尚的职业。"),
    'profit': ("The company made a big profit this year.", "公司今年获得了很大的利润。"),
    'promote': ("The school promotes reading among students.", "学校在学生中推广阅读。"),
    'proposal': ("She made a proposal to improve the system.", "她提出了改进系统的建议。"),
    'prospect': ("The job prospects for graduates are good.", "毕业生的就业前景很好。"),
    'protest': ("The students protested against the new policy.", "学生们抗议新政策。"),
    'publish': ("He published his first novel at age 25.", "他25岁时出版了他的第一部小说。"),
    'purchase': ("I purchased a new phone last week.", "我上周买了一部新手机。"),
    'pursue': ("She pursued her dream of becoming a singer.", "她追求成为歌手的梦想。"),
    'qualify': ("This exam qualifies you to be a teacher.", "通过这个考试你就有资格当老师。"),
    'quantity': ("A large quantity of food was wasted.", "大量的食物被浪费了。"),
    'range': ("The store sells a wide range of products.", "这家店卖各种各样的产品。"),
    'rare': ("Pandas are rare animals.", "熊猫是稀有动物。"),
    'reality': ("We have to face reality.", "我们必须面对现实。"),
    'recommend': ("I recommend this book to everyone.", "我向大家推荐这本书。"),
    'recover': ("She recovered quickly from her illness.", "她很快就病愈了。"),
    'reduce': ("We should reduce the use of plastic.", "我们应该减少塑料的使用。"),
    'refer': ("Please refer to the dictionary for this word.", "请查字典了解这个词。"),
    'reflect': ("His actions reflect his personality.", "他的行为反映了他的性格。"),
    'reform': ("The country needs education reform.", "这个国家需要教育改革。"),
    'regard': ("She is regarded as the best student.", "她被认为是最好的学生。"),
    'register': ("I registered for the English course.", "我报名参加了英语课程。"),
    'regulate': ("The government regulates the prices.", "政府监管价格。"),
    'reject': ("She rejected his offer of help.", "她拒绝了他提供的帮助。"),
    'relate': ("This problem relates to what we learned yesterday.", "这个问题和我们昨天学的有关。"),
    'release': ("The new movie will be released next month.", "这部新电影下个月上映。"),
    'relevant': ("This information is relevant to our research.", "这个信息与我们的研究相关。"),
    'relief': ("To my relief, the exam was easy.", "让我松了口气的是，考试很简单。"),
    'rely': ("You can rely on me.", "你可以信赖我。"),
    'remain': ("Please remain seated.", "请坐着不要动。"),
    'remark': ("She remarked on the beauty of the sunset.", "她评论了日落的美景。"),
    'remedy': ("We need to find a remedy for the situation.", "我们需要想办法补救这个情况。"),
    'remote': ("He lives in a remote village.", "他住在一个偏远的村庄。"),
    'represent': ("The red lines on the map represent roads.", "地图上的红线代表道路。"),
    'reputation': ("She has a good reputation at school.", "她在学校名声很好。"),
    'request': ("She requested permission to leave early.", "她请求允许早退。"),
    'require': ("This job requires a lot of patience.", "这份工作需要很多耐心。"),
    'research': ("He is doing research on climate change.", "他在做气候变化的研究。"),
    'reserve': ("I reserved a table at the restaurant.", "我在餐厅预订了一个位子。"),
    'resist': ("I couldn't resist eating the chocolate.", "我忍不住吃了巧克力。"),
    'resolve': ("We need to resolve this problem quickly.", "我们需要尽快解决这个问题。"),
    'resource': ("Water is an important natural resource.", "水是重要的自然资源。"),
    'respond': ("Please respond to my email as soon as possible.", "请尽快回复我的邮件。"),
    'responsible': ("Parents are responsible for their children.", "父母对他们的孩子负责。"),
    'restore': ("The old church was restored last year.", "这座老教堂去年被修复了。"),
    'restrict': ("The speed is restricted to 60 km/h here.", "这里限速每小时60公里。"),
    'reveal': ("She revealed the secret to her mother.", "她把秘密透露给了妈妈。"),
    'revenue': ("The company's annual revenue is growing.", "公司的年收入在增长。"),
    'revolution': ("The Industrial Revolution changed the world.", "工业革命改变了世界。"),
    'reward': ("She got a reward for her hard work.", "她因为努力工作得到了奖励。"),
    'ridiculous': ("That's a ridiculous idea.", "那是个荒谬的主意。"),
    'rigid': ("The school has rigid rules.", "学校有严格的规定。"),
    'routine': ("Exercise should be part of your daily routine.", "锻炼应该成为你日常作息的一部分。"),
    'sacrifice': ("Parents often sacrifice for their children.", "父母常常为孩子牺牲。"),
    'satisfy': ("Nothing can satisfy his needs.", "没有什么能满足他的需求。"),
    'schedule': ("I have a busy schedule today.", "我今天行程很紧。"),
    'security': ("The airport has tight security.", "机场有严密的安保。"),
    'sensitive': ("She is very sensitive to criticism.", "她对批评很敏感。"),
    'separate': ("The two friends were separated after graduation.", "这两个朋友毕业后分开了。"),
    'significant': ("There has been a significant improvement in your work.", "你的工作有了显著的进步。"),
    'similar': ("Your bag is similar to mine.", "你的包和我的很像。"),
    'simplify': ("The teacher simplified the problem for us.", "老师为我们简化了问题。"),
    'sincere': ("Please accept my sincere thanks.", "请接受我真诚的感谢。"),
    'solution': ("We found a solution to the problem.", "我们找到了问题的解决方案。"),
    'somehow': ("Somehow, I knew he would come.", "不知怎么地，我就知道他会来。"),
    'soul': ("Music touches the soul.", "音乐触及灵魂。"),
    'source': ("The sun is our main source of energy.", "太阳是我们主要的能量来源。"),
    'specific': ("Can you give me a specific example?", "你能给我一个具体的例子吗？"),
    'stable': ("The patient is in stable condition.", "病人情况稳定。"),
    'standard': ("Her English is of a high standard.", "她的英语水平很高。"),
    'status': ("What is your current status?", "你目前的状况是什么？"),
    'strategy': ("We need a good strategy to win the game.", "我们需要一个好策略来赢得比赛。"),
    'strength': ("Everyone has their own strengths.", "每个人都有自己的长处。"),
    'structure': ("The sentence structure is wrong.", "这个句子结构不对。"),
    'struggle': ("He struggled to lift the heavy box.", "他努力搬起那个重箱子。"),
    'substance': ("Water is a liquid substance.", "水是一种液体物质。"),
    'substitute': ("You can substitute milk with water.", "你可以用水代替牛奶。"),
    'sufficient': ("We have sufficient food for the trip.", "我们有足够的食物供旅行。"),
    'summarize': ("Can you summarize the main idea?", "你能总结一下主要观点吗？"),
    'superior': ("This product is superior to that one.", "这个产品比那个好。"),
    'surround': ("The house is surrounded by trees.", "房子被树环绕。"),
    'survey': ("We conducted a survey about eating habits.", "我们进行了一项关于饮食习惯的调查。"),
    'survive': ("Only a few people survived the accident.", "只有少数人在事故中幸存。"),
    'suspect': ("I suspect he took the money.", "我怀疑他拿了钱。"),
    'symbol': ("The dove is a symbol of peace.", "鸽子是和平的象征。"),
    'sympathy': ("I expressed my sympathy to her.", "我向她表达了同情。"),
    'system': ("China has a good education system.", "中国有良好的教育体系。"),
    'temporary': ("I found a temporary job for the summer.", "我找到了一份暑期临时工作。"),
    'tendency': ("He has a tendency to be late.", "他有迟到的倾向。"),
    'terminal': ("We met at the bus terminal.", "我们在公交总站见面了。"),
    'territory': ("This area is our territory.", "这个地区是我们的领土。"),
    'thorough': ("The doctor gave me a thorough check-up.", "医生给我做了全面检查。"),
    'threaten': ("He threatened to tell the teacher.", "他威胁说要告诉老师。"),
    'tolerate': ("I can't tolerate the noise anymore.", "我再也忍受不了这噪音了。"),
    'transform': ("The city has been transformed in recent years.", "这座城市近年来发生了翻天覆地的变化。"),
    'tremendous': ("The project was a tremendous success.", "这个项目取得了巨大的成功。"),
    'trend': ("This is the latest fashion trend.", "这是最新的时尚潮流。"),
    'typical': ("This is typical of his behavior.", "这是他典型的行为方式。"),
    'unique': ("Everyone is unique in their own way.", "每个人都是以自己独特的方式存在的。"),
    'universal': ("Music is a universal language.", "音乐是一种通用语言。"),
    'urge': ("I urge you to take this opportunity.", "我强烈建议你抓住这个机会。"),
    'utterly': ("I am utterly confused.", "我完全困惑了。"),
    'vague': ("I have only a vague memory of the event.", "我对那件事只有模糊的记忆。"),
    'valid': ("Do you have a valid reason for being late?", "你迟到有合理的理由吗？"),
    'value': ("We should value our time.", "我们应该珍惜时间。"),
    'variety': ("There is a variety of fruits in the market.", "市场上有各种各样的水果。"),
    'version': ("I have the latest version of the software.", "我有这个软件的最新版本。"),
    'victim': ("He became a victim of the accident.", "他成了事故的受害者。"),
    'violence': ("We should solve problems without violence.", "我们应该不用暴力解决问题。"),
    'virtue': ("Patience is a virtue.", "耐心是一种美德。"),
    'visible': ("The stars are visible at night.", "晚上可以看到星星。"),
    'vision': ("He has a clear vision for the future.", "他对未来有清晰的愿景。"),
    'vital': ("It is vital that you arrive on time.", "你准时到达是至关重要的。"),
    'vivid': ("I have a vivid memory of that day.", "我对那天有清晰的记忆。"),
    'voluntary': ("She does voluntary work at the hospital.", "她在医院做志愿工作。"),
    'vulnerable': ("Children are vulnerable to diseases.", "儿童容易受到疾病的侵害。"),
    'wisdom': ("With age comes wisdom.", "随着年龄增长，智慧也随之而来。"),
    'withdraw': ("I need to withdraw some money from the bank.", "我需要从银行取些钱。"),
    'witness': ("He witnessed the traffic accident.", "他目击了那场交通事故。"),
    'workforce': ("The company has a skilled workforce.", "这家公司有一支熟练的劳动力队伍。"),
}

# Read the file
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# Process senior words
for word, (ex, ex_cn) in senior_examples.items():
    escaped_ex = ex.replace("'", "\\'")
    escaped_ex_cn = ex_cn.replace("'", "\\'")
    old = f"{{'e': '{word}',"
    new = None
    # Find the line and add ex and ex_cn before closing '}'
    import re as re_module
    pattern = re_module.compile(
        r"(\{'e': '" + re_module.escape(word) + r"',[^}]+'d': '[^']*')\s*\},",
        re_module.DOTALL
    )
    def replacer(match):
        return match.group(1) + f", 'ex': '{escaped_ex}', 'ex_cn': '{escaped_ex_cn}'}},"
    content, count = pattern.subn(replacer, content)
    if count == 0:
        print(f"WARNING: Could not find word '{word}'")

# Now process junior words
for word, (ex, ex_cn) in junior_examples.items():
    escaped_ex = ex.replace("'", "\\'")
    escaped_ex_cn = ex_cn.replace("'", "\\'")
    pattern = re_module.compile(
        r"(\{'e': '" + re_module.escape(word) + r"',[^}]+'d': '[^']*')\s*\},",
        re_module.DOTALL
    )
    def replacer(match):
        return match.group(1) + f", 'ex': '{escaped_ex}', 'ex_cn': '{escaped_ex_cn}'}},"
    content, count = pattern.subn(replacer, content)
    if count == 0:
        print(f"WARNING: Junior word '{word}' not found")

# Write the modified file
with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print("Done! All example sentences added successfully.")
