const fs = require('fs');

const filePath = 'C:\\Users\\JXS\\.zcode\\workspace\\default\\shuai_jiujiu\\lib\\data\\word_bank.dart';
let content = fs.readFileSync(filePath, 'utf8');

const lines = content.split('\n');
const result = [];

// Comprehensive example sentences for each word
const examples = {
  'abandon': { ex: 'He had to abandon the project.', ex_cn: '他不得不放弃这个项目。' },
  'ability': { ex: 'She has the ability to solve this problem.', ex_cn: '她有能力解决这个问题。' },
  'abroad': { ex: 'He wants to study abroad next year.', ex_cn: '他明年想出国留学。' },
  'absence': { ex: 'His absence made the team sad.', ex_cn: '他的缺席让团队很难过。' },
  'absolute': { ex: 'I have absolute trust in her.', ex_cn: '我绝对信任她。' },
  'absorb': { ex: 'She was absorbed in reading a novel.', ex_cn: '她全神贯注地读一本小说。' },
  'abstract': { ex: 'This idea is too abstract for children.', ex_cn: '这个想法对孩子来说太抽象了。' },
  'abundant': { ex: 'This area is abundant in natural resources.', ex_cn: '这个地区自然资源丰富。' },
  'academic': { ex: 'His academic performance is excellent.', ex_cn: '他的学业成绩很优秀。' },
  'accelerate': { ex: 'The car began to accelerate.', ex_cn: '汽车开始加速。' },
  'access': { ex: 'Students have access to the library.', ex_cn: '学生可以使用图书馆。' },
  'accompany': { ex: 'I will accompany you to the airport.', ex_cn: '我会陪你去机场。' },
  'accomplish': { ex: 'He accomplished his goal at last.', ex_cn: '他终于实现了自己的目标。' },
  'accurate': { ex: 'Your answer is accurate.', ex_cn: '你的答案是准确的。' },
  'accuse': { ex: 'They accused him of stealing the money.', ex_cn: '他们指控他偷了钱。' },
  'achieve': { ex: 'She achieved her dream of becoming a doctor.', ex_cn: '她实现了成为医生的梦想。' },
  'acknowledge': { ex: 'He acknowledged making a mistake.', ex_cn: '他承认犯了一个错误。' },
  'acquire': { ex: 'We should acquire more knowledge.', ex_cn: '我们应该获得更多的知识。' },
  'adapt': { ex: 'You need to adapt to the new environment.', ex_cn: '你需要适应新环境。' },
  'adequate': { ex: 'We have adequate food for the trip.', ex_cn: '我们有足够的食物用于旅行。' },
  'adjust': { ex: 'She adjusted the temperature of the room.', ex_cn: '她调整了房间的温度。' },
  'admire': { ex: 'I admire my mother very much.', ex_cn: '我非常钦佩我的母亲。' },
  'admit': { ex: 'He admitted that he was wrong.', ex_cn: '他承认自己错了。' },
  'adopt': { ex: 'The school adopted a new teaching method.', ex_cn: '学校采用了一种新的教学方法。' },
  'advance': { ex: 'Technology has advanced a lot in recent years.', ex_cn: '近年来技术进步了很多。' },
  'advantage': { ex: 'Being tall is an advantage in basketball.', ex_cn: '个子高是打篮球的优势。' },
  'advertise': { ex: 'Companies advertise their products on TV.', ex_cn: '公司在电视上为产品做广告。' },
  'affair': { ex: 'That is my personal affair.', ex_cn: '那是我私人的事情。' },
  'affect': { ex: 'The bad weather affected our plan.', ex_cn: '坏天气影响了我们的计划。' },
  'afford': { ex: 'I cannot afford a new car now.', ex_cn: '我现在买不起一辆新车。' },
  'aggressive': { ex: 'He is too aggressive when playing games.', ex_cn: '他玩游戏时太好胜了。' },
  'agriculture': { ex: 'Agriculture is very important for our country.', ex_cn: '农业对我们国家非常重要。' },
  'allocate': { ex: 'The school allocated money for new books.', ex_cn: '学校拨出资金购买新书。' },
  'allow': { ex: 'My parents allow me to watch TV on weekends.', ex_cn: '我父母允许我周末看电视。' },
  'alternative': { ex: 'We need to find an alternative way.', ex_cn: '我们需要找到另一种方法。' },
  'amaze': { ex: 'The magician amazed the audience.', ex_cn: '魔术师让观众感到惊奇。' },
  'ambition': { ex: 'Her ambition is to become a scientist.', ex_cn: '她的志向是成为一名科学家。' },
  'analyse': { ex: 'We need to analyse the data carefully.', ex_cn: '我们需要仔细分析数据。' },
  'ancestor': { ex: 'Our ancestors lived a simple life.', ex_cn: '我们的祖先过着简单的生活。' },
  'announce': { ex: 'The teacher announced the exam results.', ex_cn: '老师宣布了考试结果。' },
  'annual': { ex: 'The school holds an annual sports meeting.', ex_cn: '学校每年举办一次运动会。' },
  'anxiety': { ex: 'He felt anxiety before the exam.', ex_cn: '考试前他感到焦虑。' },
  'apparent': { ex: 'It is apparent that she is very happy.', ex_cn: '很明显她非常开心。' },
  'appeal': { ex: 'The idea appeals to young people.', ex_cn: '这个想法吸引了年轻人。' },
  'appetite': { ex: 'I have a good appetite today.', ex_cn: '我今天胃口很好。' },
  'applaud': { ex: 'The audience applauded loudly.', ex_cn: '观众大声鼓掌。' },
  'apply': { ex: 'I want to apply for this job.', ex_cn: '我想申请这份工作。' },
  'appoint': { ex: 'They appointed him as team leader.', ex_cn: '他们任命他为队长。' },
  'appreciate': { ex: 'I appreciate your help very much.', ex_cn: '我非常感激你的帮助。' },
  'approach': { ex: 'Winter is approaching.', ex_cn: '冬天快要到了。' },
  'appropriate': { ex: 'This dress is appropriate for the party.', ex_cn: '这条裙子适合这个聚会。' },
  'approve': { ex: 'My parents approved of my decision.', ex_cn: '我父母赞同我的决定。' },
  'argue': { ex: 'Do not argue with your parents.', ex_cn: '不要和父母争论。' },
  'arrange': { ex: 'I will arrange a meeting for us.', ex_cn: '我会为我们安排一次会议。' },
  'artificial': { ex: 'This flower is artificial.', ex_cn: '这朵花是人造的。' },
  'aspect': { ex: 'We should consider every aspect of the plan.', ex_cn: '我们应该考虑计划的各个方面。' },
  'assemble': { ex: 'All students assembled in the hall.', ex_cn: '所有学生在大厅集合。' },
  'assess': { ex: 'The teacher assessed our homework.', ex_cn: '老师评估了我们的作业。' },
  'assign': { ex: 'The teacher assigned us a lot of homework.', ex_cn: '老师给我们布置了很多作业。' },
  'assist': { ex: 'Can you assist me with this task?', ex_cn: '你能协助我完成这个任务吗？' },
  'associate': { ex: 'I associate summer with swimming.', ex_cn: '我把夏天和游泳联系在一起。' },
  'assume': { ex: 'I assume you have finished your homework.', ex_cn: '我假设你已经完成了作业。' },
  'atmosphere': { ex: 'The atmosphere in the room was warm.', ex_cn: '房间里的气氛很温暖。' },
  'attach': { ex: 'Please attach the file to the email.', ex_cn: '请把文件附在邮件上。' },
  'attempt': { ex: 'She attempted to solve the problem.', ex_cn: '她试图解决这个问题。' },
  'attend': { ex: 'I will attend the meeting tomorrow.', ex_cn: '我明天会参加会议。' },
  'attitude': { ex: 'You should have a positive attitude.', ex_cn: '你应该有一个积极的态度。' },
  'attract': { ex: 'The flower attracts many butterflies.', ex_cn: '花朵吸引了许多蝴蝶。' },
  'authority': { ex: 'You need to ask the authorities for permission.', ex_cn: '你需要向当局申请许可。' },
  'available': { ex: 'This book is available in the library.', ex_cn: '这本书在图书馆可以借到。' },
  'average': { ex: 'His grades are above average.', ex_cn: '他的成绩高于平均水平。' },
  'avoid': { ex: 'You should avoid eating too much sugar.', ex_cn: '你应该避免吃太多糖。' },
  'aware': { ex: 'She is aware of the danger.', ex_cn: '她意识到了危险。' },
  'balance': { ex: 'You need to keep a balance between work and rest.', ex_cn: '你需要在工作和休息之间保持平衡。' },
  'barrier': { ex: 'Language can be a barrier to communication.', ex_cn: '语言可能是沟通的障碍。' },
  'behalf': { ex: 'I am writing on behalf of my class.', ex_cn: '我代表班级写信。' },
  'behave': { ex: 'Please behave well in class.', ex_cn: '请在课堂上表现好。' },
  'belief': { ex: 'He has a strong belief in justice.', ex_cn: '他对正义有坚定的信念。' },
  'belong': { ex: 'This book belongs to the library.', ex_cn: '这本书属于图书馆。' },
  'benefit': { ex: 'Exercise benefits our health.', ex_cn: '锻炼有益于我们的健康。' },
  'betray': { ex: 'Do not betray your friends.', ex_cn: '不要背叛你的朋友。' },
  'bother': { ex: 'Do not bother your sister while she is studying.', ex_cn: '你姐姐学习时不要打扰她。' },
  'boundary': { ex: 'The river is the boundary between the two towns.', ex_cn: '这条河是两个城镇的边界。' },
  'brilliant': { ex: 'She has a brilliant idea.', ex_cn: '她有一个绝妙的主意。' },
  'budget': { ex: 'We need to stay within our budget.', ex_cn: '我们需要控制在预算内。' },
  'burden': { ex: 'Do not be a burden to your parents.', ex_cn: '不要成为你父母的负担。' },
  'calculate': { ex: 'Please calculate the total cost.', ex_cn: '请计算总费用。' },
  'campaign': { ex: 'They launched a campaign to protect the environment.', ex_cn: '他们发起了一场保护环境的运动。' },
  'capable': { ex: 'She is capable of finishing the task alone.', ex_cn: '她有能力独自完成任务。' },
  'capacity': { ex: 'The hall has a capacity of 500 people.', ex_cn: '这个大厅能容纳500人。' },
  'capture': { ex: 'The cat captured a mouse.', ex_cn: '猫抓住了一只老鼠。' },
  'career': { ex: 'She is planning her future career.', ex_cn: '她正在规划未来的职业。' },
  'cast': { ex: 'He cast his fishing line into the river.', ex_cn: '他把钓鱼线抛进河里。' },
  'category': { ex: 'Put these books into the right category.', ex_cn: '把这些书放到正确的类别里。' },
  'cause': { ex: 'What caused the accident?', ex_cn: '什么导致了这场事故？' },
  'celebrate': { ex: 'We celebrate Christmas every year.', ex_cn: '我们每年庆祝圣诞节。' },
  'ceremony': { ex: 'The opening ceremony was wonderful.', ex_cn: '开幕式很精彩。' },
  'challenge': { ex: 'This math problem is a real challenge.', ex_cn: '这道数学题是一个真正的挑战。' },
  'character': { ex: 'She has a strong character.', ex_cn: '她性格很坚强。' },
  'charity': { ex: 'They gave money to charity.', ex_cn: '他们把钱捐给了慈善机构。' },
  'chemical': { ex: 'We studied chemical reactions in class.', ex_cn: '我们在课堂上学习了化学反应。' },
  'circumstance': { ex: 'Under no circumstances should you lie.', ex_cn: '在任何情况下你都不应该说谎。' },
  'citizen': { ex: 'He is a citizen of China.', ex_cn: '他是中国公民。' },
  'civilization': { ex: 'Ancient China had a great civilization.', ex_cn: '古代中国有伟大的文明。' },
  'claim': { ex: 'He claimed that he saw the accident.', ex_cn: '他声称看到了事故。' },
  'classify': { ex: 'We classify animals into different groups.', ex_cn: '我们把动物分成不同的类别。' },
  'climate': { ex: 'The climate here is warm and humid.', ex_cn: '这里的气候温暖湿润。' },
  'coach': { ex: 'Our coach taught us how to play better.', ex_cn: '我们的教练教我们如何打得更好。' },
  'collapse': { ex: 'The old building collapsed.', ex_cn: '那座旧建筑倒塌了。' },
  'colleague': { ex: 'My colleague helped me with the project.', ex_cn: '我的同事帮我完成了这个项目。' },
  'combine': { ex: 'We should combine theory with practice.', ex_cn: '我们应该把理论和实践结合起来。' },
  'command': { ex: 'The general commanded his soldiers to attack.', ex_cn: '将军命令士兵们进攻。' },
  'comment': { ex: 'Please leave a comment on my blog.', ex_cn: '请在我的博客上留言。' },
  'commit': { ex: 'He committed himself to helping the poor.', ex_cn: '他致力于帮助穷人。' },
  'communicate': { ex: 'We communicate with each other by email.', ex_cn: '我们通过电子邮件互相交流。' },
  'community': { ex: 'Our community has a new park.', ex_cn: '我们社区有了一个新公园。' },
  'companion': { ex: 'Dogs are good companions.', ex_cn: '狗是好的同伴。' },
  'compare': { ex: 'Do not compare yourself with others.', ex_cn: '不要把自己和别人比较。' },
  'compete': { ex: 'They compete with each other in the race.', ex_cn: '他们在比赛中互相竞争。' },
  'complain': { ex: 'She always complains about the homework.', ex_cn: '她总是抱怨作业太多。' },
  'complete': { ex: 'I completed my homework on time.', ex_cn: '我按时完成了作业。' },
  'complex': { ex: 'This is a very complex problem.', ex_cn: '这是一个非常复杂的问题。' },
  'component': { ex: 'Each component of the machine is important.', ex_cn: '机器的每个组成部分都很重要。' },
  'concentrate': { ex: 'Please concentrate on your studies.', ex_cn: '请专注于你的学习。' },
  'concept': { ex: 'This concept is difficult to understand.', ex_cn: '这个概念很难理解。' },
  'concern': { ex: 'I am concerned about your health.', ex_cn: '我很担心你的健康。' },
  'conclude': { ex: 'We concluded that the plan would work.', ex_cn: '我们得出结论，这个计划可行。' },
  'condition': { ex: 'You can join on condition that you follow the rules.', ex_cn: '你可以加入，条件是你遵守规则。' },
  'conduct': { ex: 'The scientist conducted an experiment.', ex_cn: '科学家进行了一项实验。' },
  'conference': { ex: 'The teacher is attending a conference.', ex_cn: '老师正在参加一个会议。' },
  'confess': { ex: 'He confessed to breaking the window.', ex_cn: '他承认打破了窗户。' },
  'confident': { ex: 'I am confident that I will pass the exam.', ex_cn: '我自信能通过考试。' },
  'confirm': { ex: 'Please confirm your attendance.', ex_cn: '请确认你的出席。' },
  'conflict': { ex: 'They had a conflict over the plan.', ex_cn: '他们对计划产生了冲突。' },
  'confuse': { ex: 'I often confuse him with his brother.', ex_cn: '我经常把他和他弟弟搞混。' },
  'connect': { ex: 'Connect the computer to the printer.', ex_cn: '把电脑连接到打印机。' },
  'conquer': { ex: 'She conquered her fear of speaking in public.', ex_cn: '她克服了在公众面前说话的恐惧。' },
  'conscience': { ex: 'My conscience told me to tell the truth.', ex_cn: '我的良心告诉我要说实话。' },
  'conscious': { ex: 'He was conscious of the danger.', ex_cn: '他意识到了危险。' },
  'consequence': { ex: 'He failed the exam as a consequence of not studying.', ex_cn: '由于没有学习，他考试不及格。' },
  'conservative': { ex: 'My parents are quite conservative.', ex_cn: '我的父母很保守。' },
  'consider': { ex: 'Please consider my proposal carefully.', ex_cn: '请仔细考虑我的建议。' },
  'consistent': { ex: 'His actions are consistent with his words.', ex_cn: '他的言行是一致的。' },
  'constant': { ex: 'The constant noise made me unable to sleep.', ex_cn: '持续不断的噪音让我无法入睡。' },
  'construct': { ex: 'They are constructing a new bridge.', ex_cn: '他们正在建造一座新桥。' },
  'consult': { ex: 'You should consult a doctor if you feel sick.', ex_cn: '如果你觉得不舒服，应该咨询医生。' },
  'consume': { ex: 'We consume a lot of water every day.', ex_cn: '我们每天消耗很多水。' },
  'contain': { ex: 'This box contains my old toys.', ex_cn: '这个盒子里装着我旧的玩具。' },
  'contemporary': { ex: 'I like contemporary music.', ex_cn: '我喜欢当代音乐。' },
  'content': { ex: 'He is content with his life.', ex_cn: '他对自己的生活很满意。' },
  'contest': { ex: 'She won first prize in the singing contest.', ex_cn: '她在歌唱比赛中获得了一等奖。' },
  'continent': { ex: 'Asia is the largest continent.', ex_cn: '亚洲是最大的洲。' },
  'contribute': { ex: 'Everyone should contribute to protecting the environment.', ex_cn: '每个人都应该为保护环境做贡献。' },
  'convenient': { ex: 'It is convenient to take the subway.', ex_cn: '坐地铁很方便。' },
  'convince': { ex: 'I convinced my parents to let me go.', ex_cn: '我说服了父母让我去。' },
  'cooperate': { ex: 'We should cooperate with each other.', ex_cn: '我们应该互相合作。' },
  'cope': { ex: 'She can cope with the pressure well.', ex_cn: '她能很好地应对压力。' },
  'core': { ex: 'Honesty is the core of friendship.', ex_cn: '诚实是友谊的核心。' },
  'corporate': { ex: 'He works for a large corporate company.', ex_cn: '他在一家大型公司工作。' },
  'correct': { ex: 'Please correct the mistakes in your homework.', ex_cn: '请改正你作业中的错误。' },
  'correspond': { ex: 'These two pictures do not correspond.', ex_cn: '这两张图片不对应。' },
  'council': { ex: 'The student council organized the event.', ex_cn: '学生会组织了这次活动。' },
  'courage': { ex: 'She had the courage to tell the truth.', ex_cn: '她有勇气说出真相。' },
  'crash': { ex: 'The two cars crashed into each other.', ex_cn: '两辆车相撞了。' },
  'create': { ex: 'The artist created a beautiful painting.', ex_cn: '艺术家创作了一幅美丽的画。' },
  'creature': { ex: 'Dolphins are intelligent creatures.', ex_cn: '海豚是聪明的生物。' },
  'crime': { ex: 'It is a crime to steal.', ex_cn: '偷窃是犯罪。' },
  'crisis': { ex: 'The country is facing an economic crisis.', ex_cn: '这个国家正面临经济危机。' },
  'criterion': { ex: 'What is the criterion for success?', ex_cn: '成功的标准是什么？' },
  'critical': { ex: 'Critical thinking is an important skill.', ex_cn: '批判性思维是一项重要的技能。' },
  'cultivate': { ex: 'You should cultivate good study habits.', ex_cn: '你应该培养好的学习习惯。' },
  'curious': { ex: 'Children are curious about everything.', ex_cn: '孩子们对一切都很好奇。' },
  'current': { ex: 'What is the current situation?', ex_cn: '当前的情况是什么？' },
  'custom': { ex: 'It is a custom to give gifts at Spring Festival.', ex_cn: '春节送礼是一个习俗。' },
  'cycle': { ex: 'The water cycle is a natural process.', ex_cn: '水循环是一个自然过程。' },
  'damage': { ex: 'The storm caused a lot of damage.', ex_cn: '暴风雨造成了很大的损害。' },
  'debate': { ex: 'We had a debate about environmental protection.', ex_cn: '我们就环境保护进行了辩论。' },
  'debt': { ex: 'He is in debt because of the loan.', ex_cn: '他因为贷款而负债。' },
  'decade': { ex: 'Great changes have taken place in the past decade.', ex_cn: '过去十年发生了巨大的变化。' },
  'decline': { ex: 'His health is declining.', ex_cn: '他的健康正在下降。' },
  'decorate': { ex: 'We decorated the classroom for the party.', ex_cn: '我们为派对装饰了教室。' },
  'decrease': { ex: 'The number of students decreased this year.', ex_cn: '今年的学生人数减少了。' },
  'defeat': { ex: 'Our team defeated the opponent.', ex_cn: '我们队打败了对手。' },
  'defend': { ex: 'We must defend our country.', ex_cn: '我们必须保卫我们的国家。' },
  'define': { ex: 'Can you define this word?', ex_cn: '你能给这个词下定义吗？' },
  'definite': { ex: 'I need a definite answer.', ex_cn: '我需要一个明确的答复。' },
  'degree': { ex: 'To some degree, I agree with you.', ex_cn: '在某种程度上，我同意你的看法。' },
  'delay': { ex: 'The flight was delayed due to bad weather.', ex_cn: '航班因天气不好延误了。' },
  'deliberate': { ex: 'It was a deliberate lie.', ex_cn: '那是一个故意的谎言。' },
  'delicate': { ex: 'The situation is very delicate.', ex_cn: '情况非常微妙。' },
  'deliver': { ex: 'The postman delivers letters every morning.', ex_cn: '邮递员每天早上投递信件。' },
  'demand': { ex: 'There is a high demand for this product.', ex_cn: '这个产品的需求量很大。' },
  'demonstrate': { ex: 'The teacher demonstrated the experiment.', ex_cn: '老师示范了实验。' },
  'depart': { ex: 'The train will depart at 8 o\'clock.', ex_cn: '火车将在八点出发。' },
  'depend': { ex: 'It depends on the weather.', ex_cn: '这取决于天气。' },
  'deposit': { ex: 'He deposited money in the bank.', ex_cn: '他把钱存进了银行。' },
  'depress': { ex: 'The bad news depressed everyone.', ex_cn: '坏消息让每个人都感到沮丧。' },
  'derive': { ex: 'The word derives from Latin.', ex_cn: '这个词源于拉丁语。' },
  'deserve': { ex: 'You deserve a reward for your hard work.', ex_cn: '你的努力值得奖励。' },
  'desperate': { ex: 'He was desperate for help.', ex_cn: '他极其需要帮助。' },
  'determine': { ex: 'She determined to work harder.', ex_cn: '她决心更加努力。' },
  'devote': { ex: 'She devoted herself to teaching.', ex_cn: '她致力于教学事业。' },
  'distinguish': { ex: 'Can you distinguish between the two colors?', ex_cn: '你能区分这两种颜色吗？' },
  'distribute': { ex: 'The teacher distributed the exam papers.', ex_cn: '老师分发了试卷。' },
  'diverse': { ex: 'Our school has students from diverse backgrounds.', ex_cn: '我们学校有来自不同背景的学生。' },
  'domestic': { ex: 'I prefer domestic travel.', ex_cn: '我更喜欢国内旅行。' },
  'dominate': { ex: 'The team dominated the game from start to finish.', ex_cn: '这支队伍从头到尾主导了比赛。' },
  'dramatic': { ex: 'There has been a dramatic change in the weather.', ex_cn: '天气发生了巨大的变化。' },
  'dynamic': { ex: 'She is a dynamic and energetic person.', ex_cn: '她是一个有活力、充满精力的人。' },
  'eliminate': { ex: 'We need to eliminate all the errors.', ex_cn: '我们需要消除所有错误。' },
  'emerge': { ex: 'The sun emerged from behind the clouds.', ex_cn: '太阳从云层后面出现了。' },
  'emergency': { ex: 'In an emergency, call 110.', ex_cn: '在紧急情况下，拨打110。' },
  'emotion': { ex: 'She could not control her emotions.', ex_cn: '她无法控制自己的情绪。' },
  'emphasize': { ex: 'The teacher emphasized the importance of hard work.', ex_cn: '老师强调了努力的重要性。' },
  'enable': { ex: 'This key enables you to open the door.', ex_cn: '这把钥匙使你能够开门。' },
  'encounter': { ex: 'I encountered an old friend on the street.', ex_cn: '我在街上偶遇了一位老朋友。' },
  'engage': { ex: 'She engaged in a conversation with her teacher.', ex_cn: '她和老师进行了交谈。' },
  'enormous': { ex: 'They spent an enormous amount of money.', ex_cn: '他们花了一大笔钱。' },
  'enterprise': { ex: 'He started his own enterprise.', ex_cn: '他创办了自己的企业。' },
  'enthusiasm': { ex: 'She shows great enthusiasm for music.', ex_cn: '她对音乐表现出极大的热情。' },
  'equivalent': { ex: 'One dollar is equivalent to about seven yuan.', ex_cn: '一美元大约相当于七元人民币。' },
  'essential': { ex: 'Water is essential for life.', ex_cn: '水对生命是必不可少的。' },
  'evaluate': { ex: 'We need to evaluate the situation first.', ex_cn: '我们首先需要评估情况。' },
  'evidence': { ex: 'There is no evidence to support his claim.', ex_cn: '没有证据支持他的说法。' },
  'evolve': { ex: 'Species evolve over time.', ex_cn: '物种随着时间进化。' },
  'exaggerate': { ex: 'Do not exaggerate the problem.', ex_cn: '不要夸大问题。' },
  'examine': { ex: 'The doctor examined the patient carefully.', ex_cn: '医生仔细检查了病人。' },
  'exceed': { ex: 'Do not exceed the speed limit.', ex_cn: '不要超过速度限制。' },
  'exception': { ex: 'Everyone must follow the rules without exception.', ex_cn: '每个人都必须遵守规则，没有例外。' },
  'exchange': { ex: 'We exchanged gifts at Christmas.', ex_cn: '我们在圣诞节交换了礼物。' },
  'exclude': { ex: 'The price excludes the cost of delivery.', ex_cn: '这个价格不包括运费。' },
  'execute': { ex: 'The plan was executed perfectly.', ex_cn: '计划执行得很完美。' },
  'exhibit': { ex: 'The museum exhibits many ancient artifacts.', ex_cn: '博物馆展览了许多古代文物。' },
  'expand': { ex: 'The company plans to expand its business.', ex_cn: '公司计划扩展业务。' },
  'explore': { ex: 'We explore the forest during summer camp.', ex_cn: '我们在夏令营期间探索了森林。' },
  'explosion': { ex: 'There was a loud explosion.', ex_cn: '有一声巨大的爆炸。' },
  'expose': { ex: 'Do not expose your skin to the sun too long.', ex_cn: '不要让皮肤暴露在阳光下太久。' },
  'extend': { ex: 'Could you extend the deadline?', ex_cn: '你能延长截止日期吗？' },
  'extreme': { ex: 'The weather has been extreme this year.', ex_cn: '今年的天气很极端。' },
  'facility': { ex: 'Our school has excellent sports facilities.', ex_cn: '我们学校有很好的体育设施。' },
  'factor': { ex: 'Hard work is a key factor in success.', ex_cn: '努力是成功的关键因素。' },
  'familiar': { ex: 'I am familiar with this song.', ex_cn: '我熟悉这首歌。' },
  'fascinating': { ex: 'The documentary was fascinating.', ex_cn: '这部纪录片很迷人。' },
  'flexible': { ex: 'We need a flexible schedule.', ex_cn: '我们需要一个灵活的时间表。' },
  'forecast': { ex: 'The weather forecast says it will rain.', ex_cn: '天气预报说会下雨。' },
  'fortune': { ex: 'He made a fortune by working hard.', ex_cn: '他通过努力工作赚了一大笔钱。' },
  'frequent': { ex: 'There are frequent buses to the city center.', ex_cn: '去市中心有频繁的公交车。' },
  'genuine': { ex: 'She showed genuine concern for others.', ex_cn: '她对别人表现出真诚的关心。' },
  'global': { ex: 'Global warming is a serious problem.', ex_cn: '全球变暖是一个严重的问题。' },
  'gradual': { ex: 'There has been a gradual improvement in his health.', ex_cn: '他的健康逐渐改善了。' },
  'guarantee': { ex: 'Hard work does not guarantee success.', ex_cn: '努力并不能保证成功。' },
  'harmony': { ex: 'We should live in harmony with nature.', ex_cn: '我们应该与自然和谐相处。' },
  'hesitate': { ex: 'Do not hesitate to ask for help.', ex_cn: '不要犹豫，尽管求助。' },
  'highlight': { ex: 'The report highlights the main problems.', ex_cn: '报告强调了主要问题。' },
  'horizon': { ex: 'Traveling broadens our horizons.', ex_cn: '旅行开阔我们的眼界。' },
  'ideal': { ex: 'This is an ideal place for a picnic.', ex_cn: '这是一个野餐的理想地点。' },
  'identify': { ex: 'Can you identify the man in the picture?', ex_cn: '你能认出照片中的人吗？' },
  'ignore': { ex: 'Do not ignore your parents\' advice.', ex_cn: '不要忽视父母的建议。' },
  'illustrate': { ex: 'The teacher illustrated the point with examples.', ex_cn: '老师用例子说明了这个观点。' },
  'immigrant': { ex: 'Immigrants bring new ideas to the country.', ex_cn: '移民给国家带来新的想法。' },
  'impact': { ex: 'The new policy had a great impact on education.', ex_cn: '新政策对教育产生了很大影响。' },
  'implement': { ex: 'The school implemented a new rule.', ex_cn: '学校实施了一项新规定。' },
  'imply': { ex: 'What are you trying to imply?', ex_cn: '你想要暗示什么？' },
  'impose': { ex: 'Do not impose your ideas on others.', ex_cn: '不要把你的想法强加给别人。' },
  'incredible': { ex: 'The view from the top was incredible.', ex_cn: '山顶的景色令人难以置信。' },
  'independent': { ex: 'She is very independent for her age.', ex_cn: '就她的年龄来说，她非常独立。' },
  'indicate': { ex: 'The sign indicates the way to the station.', ex_cn: '标志指示了去车站的路。' },
  'individual': { ex: 'Each individual has their own strengths.', ex_cn: '每个人都有自己独特的优势。' },
  'influence': { ex: 'My teacher had a great influence on me.', ex_cn: '我的老师对我有很大的影响。' },
  'inform': { ex: 'Please inform us of any changes.', ex_cn: '如有任何变化请通知我们。' },
  'initial': { ex: 'My initial reaction was surprise.', ex_cn: '我最初的反应是惊讶。' },
  'initiative': { ex: 'He took the initiative to help others.', ex_cn: '他主动帮助别人。' },
  'injury': { ex: 'He suffered a serious injury in the game.', ex_cn: '他在比赛中受了重伤。' },
  'innocent': { ex: 'The court found him innocent.', ex_cn: '法庭认定他是无辜的。' },
  'inspire': { ex: 'Her story inspired me to work harder.', ex_cn: '她的故事激励我更加努力。' },
  'institution': { ex: 'Schools are important educational institutions.', ex_cn: '学校是重要的教育机构。' },
  'instrument': { ex: 'She can play several musical instruments.', ex_cn: '她会演奏几种乐器。' },
  'insurance': { ex: 'You should buy health insurance.', ex_cn: '你应该买健康保险。' },
  'intellectual': { ex: 'Reading helps with intellectual development.', ex_cn: '阅读有助于智力发展。' },
  'intelligent': { ex: 'Dolphins are very intelligent animals.', ex_cn: '海豚是非常聪明的动物。' },
  'interfere': { ex: 'Do not interfere in other people\'s business.', ex_cn: '不要干涉别人的事情。' },
  'interpret': { ex: 'Can you interpret the meaning of this poem?', ex_cn: '你能解释这首诗的意思吗？' },
  'investigate': { ex: 'The police are investigating the case.', ex_cn: '警察正在调查这个案件。' },
  'involve': { ex: 'The project involves a lot of hard work.', ex_cn: '这个项目需要很多努力。' },
  'isolate': { ex: 'Do not isolate yourself from others.', ex_cn: '不要把自己和别人隔离开。' },
  'journal': { ex: 'She keeps a journal every day.', ex_cn: '她每天写日记。' },
  'judge': { ex: 'Do not judge a book by its cover.', ex_cn: '不要以貌取人。' },
  'justify': { ex: 'How can you justify your behavior?', ex_cn: '你怎么为自己的行为辩护？' },
  'keen': { ex: 'She is keen on learning new languages.', ex_cn: '她热衷于学习新语言。' },
  'launch': { ex: 'The company launched a new product.', ex_cn: '公司推出了一款新产品。' },
  'leak': { ex: 'The pipe is leaking water.', ex_cn: '水管在漏水。' },
  'legal': { ex: 'It is legal to drive at age 18.', ex_cn: '18岁开车是合法的。' },
  'liberal': { ex: 'She has liberal views on education.', ex_cn: '她对教育持有开明的观点。' },
  'likely': { ex: 'It is likely to rain this afternoon.', ex_cn: '今天下午可能会下雨。' },
  'literary': { ex: 'Lu Xun is a famous literary figure.', ex_cn: '鲁迅是一位著名的文学人物。' },
  'logic': { ex: 'Your argument lacks logic.', ex_cn: '你的论点缺乏逻辑。' },
  'maintain': { ex: 'You should maintain good health.', ex_cn: '你应该保持健康。' },
  'manufacture': { ex: 'This factory manufactures cars.', ex_cn: '这家工厂制造汽车。' },
  'measure': { ex: 'We need to take measures to solve the problem.', ex_cn: '我们需要采取措施解决问题。' },
  'mental': { ex: 'Mental health is as important as physical health.', ex_cn: '心理健康和身体健康一样重要。' },
  'minority': { ex: 'Only a minority of students agreed.', ex_cn: '只有少数学生同意。' },
  'modify': { ex: 'We need to modify our plan.', ex_cn: '我们需要修改我们的计划。' },
  'monitor': { ex: 'The nurse monitors the patient\'s condition.', ex_cn: '护士监测病人的状况。' },
  'moral': { ex: 'We should have good moral values.', ex_cn: '我们应该有良好的道德价值观。' },
  'motivate': { ex: 'The teacher motivated us to study harder.', ex_cn: '老师激励我们更努力地学习。' },
  'negotiate': { ex: 'They are negotiating the price.', ex_cn: '他们正在协商价格。' },
  'network': { ex: 'We have a wide network of friends.', ex_cn: '我们有广泛的朋友网络。' },
  'nevertheless': { ex: 'It was difficult; nevertheless, she succeeded.', ex_cn: '这很困难，尽管如此，她还是成功了。' },
  'normal': { ex: 'It is normal to feel nervous before an exam.', ex_cn: '考试前感到紧张是很正常的。' },
  'numerous': { ex: 'He has made numerous friends at school.', ex_cn: '他在学校交了很多朋友。' },
  'obey': { ex: 'We should obey the traffic rules.', ex_cn: '我们应该遵守交通规则。' },
  'obstacle': { ex: 'Lack of money is an obstacle to education.', ex_cn: '缺钱是教育的一个障碍。' },
  'obvious': { ex: 'It is obvious that she is telling the truth.', ex_cn: '很明显她在说实话。' },
  'occasion': { ex: 'I wear this dress on special occasions.', ex_cn: '我在特殊场合穿这条裙子。' },
  'occupy': { ex: 'She is occupied with her homework.', ex_cn: '她忙于做作业。' },
  'offend': { ex: 'I did not mean to offend you.', ex_cn: '我不是故意冒犯你。' },
  'oppose': { ex: 'Many people oppose the new law.', ex_cn: '很多人反对这项新法律。' },
  'organize': { ex: 'We organized a party for her birthday.', ex_cn: '我们为她的生日组织了一个派对。' },
  'original': { ex: 'That is a very original idea.', ex_cn: '那是一个非常独创的想法。' },
  'outcome': { ex: 'The outcome of the match surprised everyone.', ex_cn: '比赛的结果让所有人惊讶。' },
  'overcome': { ex: 'She overcame all the difficulties.', ex_cn: '她克服了所有的困难。' },
  'participate': { ex: 'Everyone should participate in the discussion.', ex_cn: '每个人都应该参与讨论。' },
  'particular': { ex: 'I like this particular color.', ex_cn: '我特别喜欢这个颜色。' },
  'passion': { ex: 'She has a passion for music.', ex_cn: '她对音乐充满激情。' },
  'patience': { ex: 'You need patience to learn a new language.', ex_cn: '学习一门新语言需要耐心。' },
  'perceive': { ex: 'How do you perceive this situation?', ex_cn: '你怎么看待这种情况？' },
  'perform': { ex: 'She performed a dance at the show.', ex_cn: '她在表演中跳了一支舞。' },
  'permanent': { ex: 'She found a permanent job after graduation.', ex_cn: '毕业后她找到了一份固定的工作。' },
  'permit': { ex: 'Smoking is not permitted here.', ex_cn: '这里不允许吸烟。' },
  'persist': { ex: 'If you persist, you will succeed.', ex_cn: '如果你坚持，你就会成功。' },
  'personality': { ex: 'She has a cheerful personality.', ex_cn: '她性格开朗。' },
  'perspective': { ex: 'Try to see things from a different perspective.', ex_cn: '试着从不同的角度看问题。' },
  'phenomenon': { ex: 'Rainbow is a natural phenomenon.', ex_cn: '彩虹是一种自然现象。' },
  'philosophy': { ex: 'He is interested in philosophy.', ex_cn: '他对哲学感兴趣。' },
  'physical': { ex: 'We should do physical exercise every day.', ex_cn: '我们应该每天进行体育锻炼。' },
  'policy': { ex: 'The government made a new education policy.', ex_cn: '政府制定了新的教育政策。' },
  'possess': { ex: 'She possesses great talent for singing.', ex_cn: '她拥有唱歌的天赋。' },
  'potential': { ex: 'Every student has potential to succeed.', ex_cn: '每个学生都有成功的潜力。' },
  'poverty': { ex: 'Many people live in poverty in some areas.', ex_cn: '有些地区很多人生活在贫困中。' },
  'precious': { ex: 'Time is precious; do not waste it.', ex_cn: '时间是宝贵的，不要浪费。' },
  'precise': { ex: 'You need to give a precise answer.', ex_cn: '你需要给出一个精确的答案。' },
  'predict': { ex: 'It is hard to predict the future.', ex_cn: '很难预测未来。' },
  'prejudice': { ex: 'We should fight against racial prejudice.', ex_cn: '我们应该反对种族偏见。' },
  'preserve': { ex: 'We must preserve the natural environment.', ex_cn: '我们必须保护自然环境。' },
  'pressure': { ex: 'He is under a lot of pressure from exams.', ex_cn: '他承受着考试带来的很大压力。' },
  'previous': { ex: 'I have previous experience in teaching.', ex_cn: '我有之前的教学经验。' },
  'principle': { ex: 'He sticks to his principles.', ex_cn: '他坚持自己的原则。' },
  'privilege': { ex: 'It is a privilege to study here.', ex_cn: '在这里学习是一种荣幸。' },
  'procedure': { ex: 'Follow the safety procedure carefully.', ex_cn: '仔细遵循安全程序。' },
  'profession': { ex: 'Teaching is a noble profession.', ex_cn: '教书是一个崇高的职业。' },
  'profit': { ex: 'The company made a large profit.', ex_cn: '公司获得了很大的利润。' },
  'promote': { ex: 'The school promotes reading among students.', ex_cn: '学校在学生中推广阅读。' },
  'proposal': { ex: 'He made a proposal to improve the system.', ex_cn: '他提出了改进系统的建议。' },
  'prospect': { ex: 'There are good job prospects in this field.', ex_cn: '这个领域有很好的就业前景。' },
  'protest': { ex: 'They protested against the decision.', ex_cn: '他们抗议这个决定。' },
  'publish': { ex: 'She wants to publish a book one day.', ex_cn: '她希望有一天能出版一本书。' },
  'purchase': { ex: 'I purchased a new computer yesterday.', ex_cn: '我昨天买了一台新电脑。' },
  'pursue': { ex: 'You should pursue your dreams.', ex_cn: '你应该追求你的梦想。' },
  'qualify': { ex: 'He qualified as a doctor last year.', ex_cn: '他去年取得了医生资格。' },
  'quantity': { ex: 'A large quantity of food was wasted.', ex_cn: '大量的食物被浪费了。' },
  'range': { ex: 'The store offers a wide range of products.', ex_cn: '这家商店提供各种各样的产品。' },
  'rare': { ex: 'This is a rare species of bird.', ex_cn: '这是一种稀有的鸟类。' },
  'reality': { ex: 'In reality, things are not that simple.', ex_cn: '实际上，事情没有那么简单。' },
  'recommend': { ex: 'I recommend this book to everyone.', ex_cn: '我向大家推荐这本书。' },
  'recover': { ex: 'He recovered from his illness quickly.', ex_cn: '他很快从疾病中恢复了。' },
  'reduce': { ex: 'We should reduce waste to protect the environment.', ex_cn: '我们应该减少浪费以保护环境。' },
  'refer': { ex: 'Please refer to the dictionary for the meaning.', ex_cn: '请查阅词典了解词义。' },
  'reflect': { ex: 'His actions reflect his personality.', ex_cn: '他的行为反映了他的性格。' },
  'reform': { ex: 'The education reform brought many changes.', ex_cn: '教育改革带来了很多变化。' },
  'regard': { ex: 'I regard her as my best friend.', ex_cn: '我把她看作最好的朋友。' },
  'register': { ex: 'You need to register for the course.', ex_cn: '你需要注册这门课程。' },
  'regulate': { ex: 'The government regulates the prices.', ex_cn: '政府调控价格。' },
  'reject': { ex: 'She rejected his invitation.', ex_cn: '她拒绝了他的邀请。' },
  'relate': { ex: 'This problem relates to what we learned yesterday.', ex_cn: '这个问题和我们昨天学的内容有关。' },
  'release': { ex: 'The movie will be released next month.', ex_cn: '这部电影下个月上映。' },
  'relevant': { ex: 'This information is relevant to our project.', ex_cn: '这个信息与我们的项目相关。' },
  'relief': { ex: 'To my relief, the exam was easy.', ex_cn: '让我松了一口气的是，考试很简单。' },
  'rely': { ex: 'You can rely on me for help.', ex_cn: '你可以依赖我的帮助。' },
  'remain': { ex: 'Please remain seated until the bus stops.', ex_cn: '请在公交车停下前保持坐好。' },
  'remark': { ex: 'Her remarkable progress surprised everyone.', ex_cn: '她显著的进步让所有人惊讶。' },
  'remedy': { ex: 'We need to find a remedy for the problem.', ex_cn: '我们需要找到解决问题的办法。' },
  'remote': { ex: 'He lives in a remote village.', ex_cn: '他住在一个偏远的村庄。' },
  'represent': { ex: 'Our class chose him to represent us.', ex_cn: '我们班选他代表我们。' },
  'reputation': { ex: 'She has a good reputation at school.', ex_cn: '她在学校有很好的声誉。' },
  'request': { ex: 'I requested some information from them.', ex_cn: '我向他们请求了一些信息。' },
  'require': { ex: 'This job requires a lot of patience.', ex_cn: '这份工作需要很大的耐心。' },
  'research': { ex: 'He is doing research on climate change.', ex_cn: '他正在进行气候变化研究。' },
  'reserve': { ex: 'I reserved a table at the restaurant.', ex_cn: '我在餐厅预订了一张桌子。' },
  'resist': { ex: 'I cannot resist eating chocolate.', ex_cn: '我无法抗拒不吃巧克力。' },
  'resolve': { ex: 'We need to resolve this conflict peacefully.', ex_cn: '我们需要和平解决这个冲突。' },
  'resource': { ex: 'We should use natural resources wisely.', ex_cn: '我们应该明智地使用自然资源。' },
  'respond': { ex: 'Please respond to my email as soon as possible.', ex_cn: '请尽快回复我的邮件。' },
  'responsible': { ex: 'You should be responsible for your actions.', ex_cn: '你应该为自己的行为负责。' },
  'restore': { ex: 'The old building was restored to its original state.', ex_cn: '这座旧建筑被修复到了原来的状态。' },
  'restrict': { ex: 'The speed is restricted to 60 km per hour.', ex_cn: '速度限制在每小时60公里。' },
  'reveal': { ex: 'She revealed her secret to me.', ex_cn: '她向我透露了她的秘密。' },
  'revenue': { ex: 'The company\'s revenue increased this year.', ex_cn: '公司的收入今年增加了。' },
  'revolution': { ex: 'The Industrial Revolution changed the world.', ex_cn: '工业革命改变了世界。' },
  'reward': { ex: 'She received a reward for her bravery.', ex_cn: '她因勇敢而获得了奖励。' },
  'ridiculous': { ex: 'That is a ridiculous idea.', ex_cn: '那是一个荒谬的想法。' },
  'rigid': { ex: 'The school has rigid rules.', ex_cn: '学校有严格的规定。' },
  'routine': { ex: 'I follow the same routine every morning.', ex_cn: '我每天早上遵循同样的日常安排。' },
  'sacrifice': { ex: 'Parents often sacrifice for their children.', ex_cn: '父母经常为孩子牺牲。' },
  'satisfy': { ex: 'The result satisfied everyone.', ex_cn: '结果让所有人都满意。' },
  'schedule': { ex: 'What is your schedule for tomorrow?', ex_cn: '你明天的时间表是什么？' },
  'security': { ex: 'We should pay attention to home security.', ex_cn: '我们应该注意家庭安全。' },
  'sensitive': { ex: 'She is sensitive to criticism.', ex_cn: '她对批评很敏感。' },
  'separate': { ex: 'Please separate the white clothes from the dark ones.', ex_cn: '请把白色衣物和深色衣物分开。' },
  'significant': { ex: 'There has been a significant improvement in his grades.', ex_cn: '他的成绩有了显著的提高。' },
  'similar': { ex: 'My opinion is similar to yours.', ex_cn: '我的观点和你的相似。' },
  'simplify': { ex: 'We need to simplify the process.', ex_cn: '我们需要简化这个过程。' },
  'sincere': { ex: 'Please accept my sincere apologies.', ex_cn: '请接受我真诚的道歉。' },
  'solution': { ex: 'We found a solution to the problem.', ex_cn: '我们找到了问题的解决方案。' },
  'somehow': { ex: 'Somehow, I knew you would come.', ex_cn: '不知怎么地，我就知道你会来。' },
  'soul': { ex: 'Music touches the soul.', ex_cn: '音乐触动灵魂。' },
  'source': { ex: 'The sun is the main source of energy.', ex_cn: '太阳是主要的能源来源。' },
  'specific': { ex: 'Can you give me a specific example?', ex_cn: '你能给我一个具体的例子吗？' },
  'stable': { ex: 'The patient is in stable condition.', ex_cn: '病人情况稳定。' },
  'standard': { ex: 'Living standards have improved greatly.', ex_cn: '生活水平大大提高。' },
  'status': { ex: 'What is your current status?', ex_cn: '你现在的状态是什么？' },
  'strategy': { ex: 'We need a good strategy to win the game.', ex_cn: '我们需要一个好的策略来赢得比赛。' },
  'strength': { ex: 'Everyone has their own strengths.', ex_cn: '每个人都有自己的优势。' },
  'structure': { ex: 'The building has a strong structure.', ex_cn: '这座建筑结构坚固。' },
  'struggle': { ex: 'She struggled to finish the work on time.', ex_cn: '她努力按时完成工作。' },
  'substance': { ex: 'Water and ice are the same substance.', ex_cn: '水和冰是相同的物质。' },
  'substitute': { ex: 'You can substitute honey for sugar.', ex_cn: '你可以用蜂蜜代替糖。' },
  'sufficient': { ex: 'We have sufficient time to finish the task.', ex_cn: '我们有足够的时间完成任务。' },
  'summarize': { ex: 'Please summarize the main points of the passage.', ex_cn: '请总结文章的主要要点。' },
  'superior': { ex: 'This product is superior to that one.', ex_cn: '这个产品比那个更好。' },
  'surround': { ex: 'The house is surrounded by trees.', ex_cn: '房子被树木环绕。' },
  'survey': { ex: 'We conducted a survey about student habits.', ex_cn: '我们进行了一项关于学生习惯的调查。' },
  'survive': { ex: 'Only a few people survived the accident.', ex_cn: '只有少数人在事故中幸存下来。' },
  'suspect': { ex: 'I suspect he is lying.', ex_cn: '我怀疑他在说谎。' },
  'symbol': { ex: 'The dove is a symbol of peace.', ex_cn: '鸽子是和平的象征。' },
  'sympathy': { ex: 'I have sympathy for the poor.', ex_cn: '我同情穷人。' },
  'system': { ex: 'The education system needs reform.', ex_cn: '教育体系需要改革。' },
  'temporary': { ex: 'This is only a temporary solution.', ex_cn: '这只是临时的解决方案。' },
  'tendency': { ex: 'There is a tendency for prices to rise.', ex_cn: '物价有上涨的趋势。' },
  'terminal': { ex: 'We will meet at the bus terminal.', ex_cn: '我们将在公交总站见面。' },
  'territory': { ex: 'The bird defended its territory.', ex_cn: '鸟保卫了自己的领地。' },
  'thorough': { ex: 'He gave the room a thorough cleaning.', ex_cn: '他把房间彻底打扫了一遍。' },
  'threaten': { ex: 'The storm threatened to destroy the crops.', ex_cn: '暴风雨威胁要摧毁庄稼。' },
  'tolerate': { ex: 'I cannot tolerate such noise.', ex_cn: '我无法容忍这样的噪音。' },
  'transform': { ex: 'The caterpillar transformed into a butterfly.', ex_cn: '毛毛虫变成了蝴蝶。' },
  'tremendous': { ex: 'She made tremendous progress in English.', ex_cn: '她在英语上取得了巨大的进步。' },
  'trend': { ex: 'This is the latest fashion trend.', ex_cn: '这是最新的时尚潮流。' },
  'typical': { ex: 'This is a typical example of his work.', ex_cn: '这是他作品的一个典型例子。' },
  'unique': { ex: 'Everyone has a unique personality.', ex_cn: '每个人都有独特的个性。' },
  'universal': { ex: 'Music is a universal language.', ex_cn: '音乐是一种通用的语言。' },
  'urge': { ex: 'She urged me to apply for the job.', ex_cn: '她催促我申请这份工作。' },
  'utterly': { ex: 'I am utterly confused by this question.', ex_cn: '我被这个问题完全弄糊涂了。' },
  'vague': { ex: 'I have a vague memory of that event.', ex_cn: '我对那件事有模糊的记忆。' },
  'valid': { ex: 'Your ticket is valid for three days.', ex_cn: '你的票有效期是三天。' },
  'value': { ex: 'We should value our friendship.', ex_cn: '我们应该珍惜我们的友谊。' },
  'variety': { ex: 'We have a variety of books in our school library.', ex_cn: '我们学校图书馆有各种各样的书。' },
  'version': { ex: 'This is the latest version of the software.', ex_cn: '这是这个软件的最新版本。' },
  'victim': { ex: 'He became a victim of the accident.', ex_cn: '他成了事故的受害者。' },
  'violence': { ex: 'We should solve problems without violence.', ex_cn: '我们应该用非暴力的方式解决问题。' },
  'virtue': { ex: 'Honesty is a great virtue.', ex_cn: '诚实是一种伟大的美德。' },
  'visible': { ex: 'The stars are visible at night.', ex_cn: '星星在夜晚是可见的。' },
  'vision': { ex: 'He has a clear vision of his future.', ex_cn: '他对自己的未来有清晰的愿景。' },
  'vital': { ex: 'It is vital to drink enough water every day.', ex_cn: '每天喝足够的水是至关重要的。' },
  'vivid': { ex: 'I have a vivid memory of my childhood.', ex_cn: '我对童年有生动的记忆。' },
  'voluntary': { ex: 'She does voluntary work at the hospital.', ex_cn: '她在医院做志愿工作。' },
  'vulnerable': { ex: 'Old people are vulnerable to the cold.', ex_cn: '老年人容易受寒冷的影响。' },
  'wisdom': { ex: 'With age comes wisdom.', ex_cn: '随着年龄增长的是智慧。' },
  'withdraw': { ex: 'He withdrew money from the bank.', ex_cn: '他从银行取了钱。' },
  'witness': { ex: 'She witnessed the accident on her way home.', ex_cn: '她在回家的路上目击了事故。' },
  'workforce': { ex: 'The company has a skilled workforce.', ex_cn: '公司拥有一支熟练的劳动力队伍。' },
  // Junior words
  'the': { ex: 'The sun rises in the east.', ex_cn: '太阳从东方升起。' },
  'be': { ex: 'She wants to be a teacher in the future.', ex_cn: '她将来想成为一名老师。' },
  'and': { ex: 'I like apples and oranges.', ex_cn: '我喜欢苹果和橙子。' },
  'a': { ex: 'There is a book on the desk.', ex_cn: '桌子上有一本书。' },
  'to': { ex: 'I go to school by bus every day.', ex_cn: '我每天坐公交车去上学。' },
  'of': { ex: 'This is a picture of my family.', ex_cn: '这是我家庭的一张照片。' },
  'in': { ex: 'She is reading in the library.', ex_cn: '她正在图书馆里读书。' },
  'have': { ex: 'I have two brothers and one sister.', ex_cn: '我有两个兄弟和一个妹妹。' },
  'it': { ex: 'It is raining outside.', ex_cn: '外面正在下雨。' },
  'for': { ex: 'I have been waiting for an hour.', ex_cn: '我已经等了一个小时。' },
  'not': { ex: 'I do not like getting up early.', ex_cn: '我不喜欢早起。' },
  'on': { ex: 'The cat is sleeping on the sofa.', ex_cn: '猫正在沙发上睡觉。' },
  'with': { ex: 'I go to the park with my friends.', ex_cn: '我和朋友们去公园。' },
  'he': { ex: 'He is the tallest boy in our class.', ex_cn: '他是我们班最高的男孩。' },
  'as': { ex: 'She works as a nurse in the hospital.', ex_cn: '她在医院做护士工作。' },
  'you': { ex: 'You are my best friend forever.', ex_cn: '你永远是我最好的朋友。' },
  'do': { ex: 'What do you want to do today?', ex_cn: '你今天想做什么？' },
  'at': { ex: 'She is at home right now.', ex_cn: '她现在在家。' },
  'this': { ex: 'This is my favorite book.', ex_cn: '这是我最喜欢的书。' },
  'but': { ex: 'I am tired but very happy.', ex_cn: '我很累但是很开心。' },
  'his': { ex: 'His name is Li Ming.', ex_cn: '他的名字是李明。' },
  'by': { ex: 'I go to school by bike.', ex_cn: '我骑自行车去上学。' },
  'from': { ex: 'She comes from a small village.', ex_cn: '她来自一个小村庄。' },
  'they': { ex: 'They are playing basketball on the playground.', ex_cn: '他们正在操场上打篮球。' },
  'we': { ex: 'We should help each other.', ex_cn: '我们应该互相帮助。' },
  'say': { ex: 'What did you say to your mother?', ex_cn: '你跟你妈妈说了什么？' },
  'her': { ex: 'I gave her a birthday present.', ex_cn: '我给了她一份生日礼物。' },
  'she': { ex: 'She sings very beautifully.', ex_cn: '她唱歌非常好听。' },
  'or': { ex: 'Do you want tea or coffee?', ex_cn: '你想要茶还是咖啡？' },
  'an': { ex: 'She is an honest and kind girl.', ex_cn: '她是一个诚实善良的女孩。' },
  'will': { ex: 'I will call you when I arrive.', ex_cn: '我到的时候会打电话给你。' },
  'my': { ex: 'My house is near the school.', ex_cn: '我的家在学校附近。' },
  'one': { ex: 'One plus one equals two.', ex_cn: '一加一等于二。' },
  'all': { ex: 'All the students passed the exam.', ex_cn: '所有学生都通过了考试。' },
  'would': { ex: 'Would you like a cup of tea?', ex_cn: '你想要一杯茶吗？' },
  'there': { ex: 'There are many flowers in the garden.', ex_cn: '花园里有很多花。' },
  'their': { ex: 'Their school is bigger than ours.', ex_cn: '他们的学校比我们的大。' },
  'what': { ex: 'What is your favorite subject?', ex_cn: '你最喜欢的科目是什么？' },
  'so': { ex: 'It was so cold that I stayed at home.', ex_cn: '天太冷了，所以我呆在家里。' },
  'up': { ex: 'Please stand up when the teacher comes in.', ex_cn: '老师进来时请起立。' },
  'out': { ex: 'Let us go out for a walk after dinner.', ex_cn: '晚饭后我们出去散步吧。' },
  'if': { ex: 'If it rains tomorrow, we will stay at home.', ex_cn: '如果明天下雨，我们就呆在家里。' },
  'about': { ex: 'Tell me about your school life.', ex_cn: '告诉我关于你的学校生活。' },
  'who': { ex: 'Who is the girl standing over there?', ex_cn: '站在那边的女孩是谁？' },
  'get': { ex: 'I get up at six o\'clock every morning.', ex_cn: '我每天早上六点起床。' },
  'which': { ex: 'Which color do you prefer, red or blue?', ex_cn: '你更喜欢哪个颜色，红色还是蓝色？' },
  'go': { ex: 'I go to the library every weekend.', ex_cn: '我每个周末去图书馆。' },
  'me': { ex: 'Please pass me the salt.', ex_cn: '请把盐递给我。' },
  'when': { ex: 'When do you usually go to bed?', ex_cn: '你通常什么时候睡觉？' },
  'make': { ex: 'My mother makes breakfast for me every morning.', ex_cn: '我妈妈每天早上为我做早餐。' },
  'can': { ex: 'I can swim across the river.', ex_cn: '我能游过这条河。' },
  'like': { ex: 'I like reading books in my free time.', ex_cn: '我喜欢在空闲时间读书。' },
  'time': { ex: 'What time does the class begin?', ex_cn: '课什么时候开始？' },
  'no': { ex: 'There is no water in the bottle.', ex_cn: '瓶子里没有水。' },
  'just': { ex: 'I just finished my homework.', ex_cn: '我刚刚完成作业。' },
  'him': { ex: 'I saw him playing basketball yesterday.', ex_cn: '我昨天看见他在打篮球。' },
  'know': { ex: 'Do you know the answer to this question?', ex_cn: '你知道这个问题的答案吗？' },
  'people': { ex: 'Many people like to travel during holidays.', ex_cn: '很多人喜欢在假期旅行。' },
  'year': { ex: 'I will graduate from middle school next year.', ex_cn: '我明年中学毕业。' },
  'your': { ex: 'Your smile is very beautiful.', ex_cn: '你的微笑很美丽。' },
  'good': { ex: 'She is a good student and always works hard.', ex_cn: '她是个好学生，总是很努力。' },
  'some': { ex: 'I need to buy some food for dinner.', ex_cn: '我需要买一些晚餐的食物。' },
  'could': { ex: 'Could you please help me with this problem?', ex_cn: '你能帮我解决这个问题吗？' },
  'them': { ex: 'I gave them the books they needed.', ex_cn: '我把他们需要的书给了他们。' },
  'see': { ex: 'I can see a bird flying in the sky.', ex_cn: '我能看见一只鸟在天空中飞翔。' },
  'other': { ex: 'We should respect each other.', ex_cn: '我们应该互相尊重。' },
  'than': { ex: 'She is taller than her younger sister.', ex_cn: '她比她的妹妹高。' },
  'then': { ex: 'First I will study, and then I will play.', ex_cn: '首先我会学习，然后我会玩。' },
  'now': { ex: 'I am doing my homework now.', ex_cn: '我现在正在做作业。' },
  'look': { ex: 'Look at the blackboard, please.', ex_cn: '请看黑板。' },
  'only': { ex: 'She is the only girl in the football team.', ex_cn: '她是足球队里唯一的女孩。' },
  'come': { ex: 'Come here and look at this picture.', ex_cn: '过来看这张图片。' },
  'its': { ex: 'The dog is wagging its tail.', ex_cn: '狗在摇尾巴。' },
  'over': { ex: 'The game is over, and we won.', ex_cn: '比赛结束了，我们赢了。' },
  'think': { ex: 'I think you should tell the truth.', ex_cn: '我认为你应该说实话。' },
  'also': { ex: 'She can speak English and also French.', ex_cn: '她会说英语，也会说法语。' },
  'back': { ex: 'I will come back before dinner.', ex_cn: '我会在晚饭前回来。' },
  'after': { ex: 'Let us play football after school.', ex_cn: '放学后我们去踢足球吧。' },
  'how': { ex: 'How do you go to school every day?', ex_cn: '你每天怎么去上学？' },
  'our': { ex: 'Our classroom is clean and bright.', ex_cn: '我们的教室干净明亮。' },
  'work': { ex: 'My father goes to work at eight every morning.', ex_cn: '我爸爸每天早上八点去上班。' },
  'first': { ex: 'She was the first person to arrive at school.', ex_cn: '她是第一个到校的人。' },
  'well': { ex: 'She plays the piano very well.', ex_cn: '她钢琴弹得很好。' },
  'way': { ex: 'Can you tell me the way to the station?', ex_cn: '你能告诉我去车站的路吗？' },
  'even': { ex: 'She is so smart that she can even solve this hard problem.', ex_cn: '她如此聪明，甚至能解决这个难题。' },
  'new': { ex: 'I bought a new pair of shoes yesterday.', ex_cn: '我昨天买了一双新鞋。' },
  'want': { ex: 'I want to become a scientist when I grow up.', ex_cn: '我长大后想成为一名科学家。' },
  'because': { ex: 'I am happy because I got a good grade.', ex_cn: '我很开心，因为我取得了好成绩。' },
  'any': { ex: 'Do you have any questions to ask?', ex_cn: '你有什么问题要问吗？' },
  'these': { ex: 'These flowers are very beautiful.', ex_cn: '这些花非常漂亮。' },
  'give': { ex: 'Please give me a glass of water.', ex_cn: '请给我一杯水。' },
  'day': { ex: 'Every day is a new beginning.', ex_cn: '每一天都是新的开始。' },
  'most': { ex: 'Most students in our class like English.', ex_cn: '我们班大多数学生喜欢英语。' },
  'us': { ex: 'Let us go to the park together.', ex_cn: '我们一起去公园吧。' },
  'great': { ex: 'That is a great idea! Let us do it.', ex_cn: '那是个好主意！我们去做吧。' },
  'tell': { ex: 'Tell me a story, please.', ex_cn: '请给我讲个故事吧。' },
  'very': { ex: 'It is very cold outside today.', ex_cn: '今天外面很冷。' },
  'teacher': { ex: 'Our teacher is very kind to us.', ex_cn: '我们的老师对我们很好。' },
  'student': { ex: 'Each student has a dream for the future.', ex_cn: '每个学生都对未来有梦想。' },
  'mother': { ex: 'My mother cooks delicious food for us.', ex_cn: '我妈妈给我们做美味的食物。' },
  'father': { ex: 'My father is a doctor in the hospital.', ex_cn: '我爸爸是医院里的一名医生。' },
  'brother': { ex: 'My older brother helps me with my homework.', ex_cn: '我哥哥帮我做作业。' },
  'sister': { ex: 'My younger sister likes to draw pictures.', ex_cn: '我妹妹喜欢画画。' },
  'friend': { ex: 'A true friend is always there for you.', ex_cn: '真正的朋友永远在你身边。' },
  'school': { ex: 'I walk to school every morning.', ex_cn: '我每天早上步行去上学。' },
  'book': { ex: 'I am reading an interesting book.', ex_cn: '我正在读一本有趣的书。' },
  'pen': { ex: 'May I borrow your pen?', ex_cn: '我能借用你的钢笔吗？' },
  'desk': { ex: 'There is a lamp on the desk.', ex_cn: '桌子上有一盏台灯。' },
  'chair': { ex: 'Please sit on the chair.', ex_cn: '请坐在椅子上。' },
  'room': { ex: 'Please clean your room before going out.', ex_cn: '出去前请打扫你的房间。' },
  'door': { ex: 'Please close the door when you leave.', ex_cn: '离开时请关上门。' },
  'window': { ex: 'Open the window and let some fresh air in.', ex_cn: '打开窗户让新鲜空气进来。' },
  'table': { ex: 'Put your books on the table.', ex_cn: '把你的书放在桌子上。' },
  'food': { ex: 'We need food and water to survive.', ex_cn: '我们需要食物和水来生存。' },
  'water': { ex: 'Drink more water every day.', ex_cn: '每天要多喝水。' },
  'milk': { ex: 'I drink a glass of milk every morning.', ex_cn: '我每天早上喝一杯牛奶。' },
  'rice': { ex: 'We eat rice for lunch every day.', ex_cn: '我们每天午饭吃米饭。' },
  'meat': { ex: 'I do not eat too much meat.', ex_cn: '我吃不太多肉。' },
  'fruit': { ex: 'Eating fruit is good for your health.', ex_cn: '吃水果对你的健康有好处。' },
  'apple': { ex: 'An apple a day keeps the doctor away.', ex_cn: '一天一苹果，医生远离我。' },
  'banana': { ex: 'Bananas are yellow and sweet.', ex_cn: '香蕉是黄色的，很甜。' },
  'orange': { ex: 'I like to drink orange juice.', ex_cn: '我喜欢喝橙汁。' },
  'color': { ex: 'What color is your new bag?', ex_cn: '你的新书包是什么颜色的？' },
  'red': { ex: 'The red flowers are very beautiful.', ex_cn: '红色的花非常漂亮。' },
  'blue': { ex: 'The sky is blue and clear today.', ex_cn: '今天天空湛蓝清澈。' },
  'green': { ex: 'The grass is green in spring.', ex_cn: '春天草地是绿色的。' },
  'yellow': { ex: 'The yellow leaves fall in autumn.', ex_cn: '黄色的叶子在秋天落下。' },
  'white': { ex: 'Snow is white and pure.', ex_cn: '雪是白色的，很纯净。' },
  'black': { ex: 'Black is my favorite color.', ex_cn: '黑色是我最喜欢的颜色。' },
  'big': { ex: 'Our school has a big playground.', ex_cn: '我们学校有一个大操场。' },
  'small': { ex: 'The cat is still very small.', ex_cn: '这只猫还很小。' },
  'long': { ex: 'The Great Wall is very long.', ex_cn: '长城非常长。' },
  'short': { ex: 'She has short hair.', ex_cn: '她留着短发。' },
  'tall': { ex: 'The tall building is our school library.', ex_cn: '那座高楼是我们的学校图书馆。' },
  'old': { ex: 'My grandfather is seventy years old.', ex_cn: '我的祖父七十岁了。' },
  'young': { ex: 'Young people should work hard for their dreams.', ex_cn: '年轻人应该为梦想努力奋斗。' },
  'hot': { ex: 'It is very hot in summer.', ex_cn: '夏天天气很热。' },
  'cold': { ex: 'I caught a cold last week.', ex_cn: '我上周感冒了。' },
  'warm': { ex: 'Spring is warm and comfortable.', ex_cn: '春天温暖舒适。' },
  'cool': { ex: 'It is cool in autumn.', ex_cn: '秋天天气凉爽。' },
  'happy': { ex: 'I am very happy to see you.', ex_cn: '我很高兴见到你。' },
  'sad': { ex: 'She felt sad when her friend moved away.', ex_cn: '她的朋友搬走后她感到难过。' },
  'angry': { ex: 'Do not be angry with me.', ex_cn: '不要生我的气。' },
  'tired': { ex: 'I am tired after running for an hour.', ex_cn: '跑了一个小时后我累了。' },
  'hungry': { ex: 'I am hungry; let us get something to eat.', ex_cn: '我饿了，我们去吃点东西吧。' },
  'thirsty': { ex: 'Drink some water if you are thirsty.', ex_cn: '如果你渴了，喝点水。' },
  'beautiful': { ex: 'The flowers in the garden are beautiful.', ex_cn: '花园里的花很美丽。' },
  'ugly': { ex: 'The ugly duckling became a beautiful swan.', ex_cn: '丑小鸭变成了美丽的天鹅。' },
  'rich': { ex: 'The city is rich in history and culture.', ex_cn: '这座城市富有历史和文化。' },
  'poor': { ex: 'We should help poor people.', ex_cn: '我们应该帮助穷人。' },
  'easy': { ex: 'This math problem is very easy.', ex_cn: '这道数学题很容易。' },
  'difficult': { ex: 'Learning a new language is difficult but fun.', ex_cn: '学习一门新语言很难但很有趣。' },
  'important': { ex: 'It is important to study hard.', ex_cn: '努力学习很重要。' },
  'different': { ex: 'My idea is different from yours.', ex_cn: '我的想法和你的不同。' },
  'same': { ex: 'We go to the same school.', ex_cn: '我们去同一所学校。' },
  'much': { ex: 'How much is this book?', ex_cn: '这本书多少钱？' },
  'many': { ex: 'How many students are in your class?', ex_cn: '你们班有多少学生？' },
  'little': { ex: 'There is a little milk in the cup.', ex_cn: '杯子里有一点牛奶。' },
  'every': { ex: 'I go to the library every week.', ex_cn: '我每周都去图书馆。' },
  'right': { ex: 'You are right; I agree with you.', ex_cn: '你是对的，我同意你。' },
  'wrong': { ex: 'Something is wrong with my computer.', ex_cn: '我的电脑出了点问题。' },
  'real': { ex: 'This is a real diamond.', ex_cn: '这是一颗真钻石。' },
  'true': { ex: 'Her dream finally came true.', ex_cn: '她的梦想终于实现了。' },
  'full': { ex: 'The bus is full of people.', ex_cn: '公交车里挤满了人。' },
  'glad': { ex: 'I am glad to meet you.', ex_cn: '很高兴见到你。' },
  'sorry': { ex: 'I am sorry for being late.', ex_cn: '很抱歉我迟到了。' },
  'sure': { ex: 'Are you sure about the answer?', ex_cn: '你确定这个答案吗？' },
  'clear': { ex: 'The water is very clear.', ex_cn: '水很清澈。' },
  'clean': { ex: 'Please clean your room.', ex_cn: '请打扫你的房间。' },
  'dirty': { ex: 'Your shoes are dirty; clean them.', ex_cn: '你的鞋脏了，擦干净吧。' },
  'fast': { ex: 'He runs very fast.', ex_cn: '他跑得很快。' },
  'slow': { ex: 'The turtle is slow but steady.', ex_cn: '乌龟很慢但是很稳。' },
  'early': { ex: 'I get up early every morning.', ex_cn: '我每天早上早起。' },
  'late': { ex: 'Do not be late for school again.', ex_cn: '上学不要再迟到了。' },
  'far': { ex: 'How far is it from here to the airport?', ex_cn: '从这里到机场有多远？' },
  'near': { ex: 'There is a supermarket near my home.', ex_cn: '我家附近有一个超市。' },
  'open': { ex: 'Please open the window.', ex_cn: '请打开窗户。' },
  'close': { ex: 'Close the door before you leave.', ex_cn: '离开前关上门。' },
  'begin': { ex: 'The class begins at eight o\'clock.', ex_cn: '八点开始上课。' },
  'finish': { ex: 'I finished reading the book yesterday.', ex_cn: '我昨天读完了这本书。' },
  'start': { ex: 'Let us start the game now.', ex_cn: '我们现在开始游戏吧。' },
  'stop': { ex: 'The rain stopped an hour ago.', ex_cn: '雨一个小时前停了。' },
  'keep': { ex: 'Please keep quiet in the library.', ex_cn: '请在图书馆保持安静。' },
  'help': { ex: 'Can you help me with my homework?', ex_cn: '你能帮我做作业吗？' },
  'love': { ex: 'I love my family very much.', ex_cn: '我非常爱我的家人。' },
  'hate': { ex: 'I hate getting up early on weekends.', ex_cn: '我讨厌周末早起。' },
  'hope': { ex: 'I hope you can come to my party.', ex_cn: '我希望你能来参加我的派对。' },
  'wish': { ex: 'I wish you a happy birthday.', ex_cn: '我祝你生日快乐。' },
  'need': { ex: 'You need to finish your homework first.', ex_cn: '你需要先完成作业。' },
  'find': { ex: 'I cannot find my keys anywhere.', ex_cn: '我到处都找不到我的钥匙。' },
  'call': { ex: 'I will call you tonight.', ex_cn: '我今晚会打电话给你。' },
  'show': { ex: 'Can you show me your new bike?', ex_cn: '你能给我看看你的新自行车吗？' },
  'ask': { ex: 'Ask your teacher if you have questions.', ex_cn: '如果你有问题就问老师。' },
  'answer': { ex: 'Please answer my question.', ex_cn: '请回答我的问题。' },
  'remember': { ex: 'Remember to lock the door before leaving.', ex_cn: '离开前记得锁门。' },
  'forget': { ex: 'Do not forget to bring your homework tomorrow.', ex_cn: '明天别忘了带作业。' },
  'try': { ex: 'Try your best to achieve your goal.', ex_cn: '尽你最大的努力去实现目标。' },
  'learn': { ex: 'We should learn from our mistakes.', ex_cn: '我们应该从错误中学习。' },
  'teach': { ex: 'My mother teaches me to cook.', ex_cn: '我妈妈教我做饭。' },
  'study': { ex: 'I study English every evening.', ex_cn: '我每天晚上学习英语。' },
  'read': { ex: 'I like to read novels in my free time.', ex_cn: '我喜欢在空闲时间读小说。' },
  'write': { ex: 'Please write down your name on the paper.', ex_cn: '请在纸上写下你的名字。' },
  'listen': { ex: 'Listen carefully to the teacher.', ex_cn: '仔细听老师讲。' },
  'speak': { ex: 'Can you speak English?', ex_cn: '你会说英语吗？' },
  'talk': { ex: 'They are talking about the movie.', ex_cn: '他们正在谈论那部电影。' },
  'walk': { ex: 'Let us go for a walk after dinner.', ex_cn: '晚饭后我们去散步吧。' },
  'run': { ex: 'He runs faster than anyone in our class.', ex_cn: '他跑得比我们班任何人都快。' },
  'swim': { ex: 'I learned to swim last summer.', ex_cn: '我去年夏天学会了游泳。' },
  'sing': { ex: 'She sings a song for the class.', ex_cn: '她为全班唱了一首歌。' },
  'dance': { ex: 'They dance together at the party.', ex_cn: '他们在派对上一起跳舞。' },
  'draw': { ex: 'I like to draw pictures of animals.', ex_cn: '我喜欢画动物的图画。' },
  'buy': { ex: 'I want to buy a present for my mother.', ex_cn: '我想给妈妈买一份礼物。' },
  'sell': { ex: 'This store sells school supplies.', ex_cn: '这家店卖学习用品。' },
  'pay': { ex: 'I paid ten yuan for the book.', ex_cn: '我付了十元买了这本书。' },
  'cost': { ex: 'The new phone costs too much.', ex_cn: '这部新手机太贵了。' },
  'spend': { ex: 'I spend two hours doing homework every day.', ex_cn: '我每天花两个小时做作业。' },
  'bring': { ex: 'Please bring your notebook tomorrow.', ex_cn: '明天请带上你的笔记本。' },
  'carry': { ex: 'Let me carry the heavy box for you.', ex_cn: '让我帮你搬这个重箱子。' },
  'catch': { ex: 'I need to catch the early bus tomorrow.', ex_cn: '我明天需要赶早班公交车。' },
  'drive': { ex: 'My father drives me to school every day.', ex_cn: '我爸爸每天开车送我去上学。' },
  'fly': { ex: 'I will fly to Beijing next week.', ex_cn: '我下周要飞往北京。' },
  'grow': { ex: 'I want to be a teacher when I grow up.', ex_cn: '我长大后想成为一名老师。' },
  'live': { ex: 'I live in a small town near the sea.', ex_cn: '我住在一个海边的小镇。' },
  'die': { ex: 'The old man died of illness.', ex_cn: '那位老人死于疾病。' },
  'feel': { ex: 'I feel very happy today.', ex_cn: '我今天感到很开心。' },
  'smell': { ex: 'The flowers smell wonderful.', ex_cn: '这些花闻起来很香。' },
  'taste': { ex: 'The food tastes delicious.', ex_cn: '这食物尝起来很美味。' },
  'sound': { ex: 'That sounds like a good idea.', ex_cn: '那听起来是个好主意。' },
  'become': { ex: 'She became a teacher after graduation.', ex_cn: '她毕业后成为了一名老师。' },
  'leave': { ex: 'I leave home for school at seven.', ex_cn: '我七点离开家去上学。' },
  'meet': { ex: 'Nice to meet you.', ex_cn: '很高兴认识你。' },
  'lose': { ex: 'Do not lose your keys again.', ex_cn: '不要再把你的钥匙弄丢了。' },
  'win': { ex: 'Our team won the basketball game.', ex_cn: '我们队赢了篮球比赛。' },
  'wear': { ex: 'You should wear a coat in winter.', ex_cn: '冬天你应该穿外套。' },
  'put': { ex: 'Put your books in your bag.', ex_cn: '把你的书放进包里。' },
  'cut': { ex: 'Be careful not to cut your finger.', ex_cn: '小心不要割到手指。' },
  'push': { ex: 'Push the door to open it.', ex_cn: '推门打开它。' },
  'pull': { ex: 'Pull the rope as hard as you can.', ex_cn: '用力拉绳子。' },
  'throw': { ex: 'Do not throw rubbish on the ground.', ex_cn: '不要在地上扔垃圾。' },
  'turn': { ex: 'Please turn on the light.', ex_cn: '请打开灯。' },
  'fall': { ex: 'Be careful not to fall down.', ex_cn: '小心不要摔倒。' },
  'stand': { ex: 'Please stand up when answering questions.', ex_cn: '回答问题时请起立。' },
  'sit': { ex: 'Please sit down and have a rest.', ex_cn: '请坐下来休息一下。' },
  'sleep': { ex: 'I need at least eight hours of sleep.', ex_cn: '我至少需要八小时的睡眠。' },
  'wake': { ex: 'I usually wake up at six in the morning.', ex_cn: '我通常早上六点醒来。' },
  'wash': { ex: 'Wash your hands before eating.', ex_cn: '饭前要洗手。' },
  'cook': { ex: 'My mother cooks dinner for us every day.', ex_cn: '我妈妈每天为我们做晚饭。' },
  'eat': { ex: 'Let us eat out tonight.', ex_cn: '我们今晚出去吃吧。' },
  'drink': { ex: 'You should drink more water.', ex_cn: '你应该多喝水。' },
  'play': { ex: 'Children love to play in the park.', ex_cn: '孩子们喜欢在公园里玩。' },
  'game': { ex: 'We played a fun game at the party.', ex_cn: '我们在派对上玩了一个有趣的游戏。' },
  'sport': { ex: 'Doing sports is good for health.', ex_cn: '做运动对健康有好处。' },
  'ball': { ex: 'The red ball is mine.', ex_cn: '那个红色的球是我的。' },
  'team': { ex: 'Our team won the game.', ex_cn: '我们队赢了比赛。' },
  'music': { ex: 'I like listening to music.', ex_cn: '我喜欢听音乐。' },
  'song': { ex: 'This is my favorite song.', ex_cn: '这是我最喜欢的歌。' },
  'movie': { ex: 'We watched a movie last night.', ex_cn: '我们昨晚看了一部电影。' },
  'story': { ex: 'My grandma tells me a story before bed.', ex_cn: '我奶奶睡觉前给我讲故事。' },
  'picture': { ex: 'Please draw a picture of your family.', ex_cn: '请画一张你家庭的图画。' },
  'computer': { ex: 'I use the computer to do my homework.', ex_cn: '我用电脑做作业。' },
  'phone': { ex: 'My phone number is 123456789.', ex_cn: '我的电话号码是123456789。' },
  'city': { ex: 'Beijing is a big and beautiful city.', ex_cn: '北京是一座美丽的大城市。' },
  'country': { ex: 'China is a great country with a long history.', ex_cn: '中国是一个有着悠久历史的伟大国家。' },
  'world': { ex: 'I want to travel around the world one day.', ex_cn: '我希望有一天能环游世界。' },
  'river': { ex: 'The Yellow River is a long river in China.', ex_cn: '黄河是中国的一条长河。' },
  'mountain': { ex: 'We climbed the mountain last weekend.', ex_cn: '我们上周末爬了山。' },
  'sea': { ex: 'I like to swim in the sea.', ex_cn: '我喜欢在海里游泳。' },
  'sky': { ex: 'Birds are flying in the sky.', ex_cn: '鸟儿在天空中飞翔。' },
  'sun': { ex: 'The sun rises in the east.', ex_cn: '太阳从东方升起。' },
  'moon': { ex: 'The moon looks bright tonight.', ex_cn: '今晚的月亮看起来很亮。' },
  'star': { ex: 'There are many stars in the sky at night.', ex_cn: '夜晚的天空中有很多星星。' },
  'tree': { ex: 'The tree in front of our school is very old.', ex_cn: '我们学校前面的那棵树很老了。' },
  'flower': { ex: 'These flowers smell sweet.', ex_cn: '这些花闻起来很香。' },
  'animal': { ex: 'I love animals, especially dogs and cats.', ex_cn: '我喜爱动物，特别是狗和猫。' },
  'dog': { ex: 'I walk my dog every evening.', ex_cn: '我每天晚上遛狗。' },
  'cat': { ex: 'The cat is sleeping on the sofa.', ex_cn: '猫在沙发上睡觉。' },
  'bird': { ex: 'A bird is singing in the tree.', ex_cn: '一只鸟在树上唱歌。' },
  'fish': { ex: 'I went fishing with my father last Sunday.', ex_cn: '我上周日和爸爸去钓鱼了。' },
  'horse': { ex: 'He is learning to ride a horse.', ex_cn: '他正在学习骑马。' },
  'body': { ex: 'Exercise keeps our body healthy.', ex_cn: '锻炼让我们的身体保持健康。' },
  'head': { ex: 'She shook her head to say no.', ex_cn: '她摇头说不。' },
  'face': { ex: 'She has a smiling face.', ex_cn: '她有一张微笑的脸。' },
  'eye': { ex: 'She has big blue eyes.', ex_cn: '她有一双蓝色的大眼睛。' },
  'ear': { ex: 'The rabbit has long ears.', ex_cn: '兔子有长耳朵。' },
  'nose': { ex: 'He has a runny nose because of the cold.', ex_cn: '他因为感冒流鼻涕。' },
  'mouth': { ex: 'Open your mouth and say "Ah".', ex_cn: '张开嘴说"啊"。' },
  'hand': { ex: 'Wash your hands before meals.', ex_cn: '饭前要洗手。' },
  'foot': { ex: 'I go to school on foot every day.', ex_cn: '我每天步行去上学。' },
  'arm': { ex: 'She broke her arm in the accident.', ex_cn: '她在事故中摔断了手臂。' },
  'leg': { ex: 'My legs are tired after the long walk.', ex_cn: '走了很长的路后我的腿很累。' },
  'hair': { ex: 'She has long black hair.', ex_cn: '她有一头黑色的长发。' },
  'heart': { ex: 'I learn English by heart.', ex_cn: '我用心学习英语。' },
  'health': { ex: 'You should take care of your health.', ex_cn: '你应该注意你的健康。' },
  'doctor': { ex: 'You should see a doctor when you are sick.', ex_cn: '生病时应该去看医生。' },
  'nurse': { ex: 'The nurse takes care of the patients.', ex_cn: '护士照顾病人。' },
  'hospital': { ex: 'My mother works in a hospital.', ex_cn: '我妈妈在一家医院工作。' },
  'medicine': { ex: 'Take this medicine three times a day.', ex_cn: '这个药一天吃三次。' },
  'shop': { ex: 'I go shopping with my mom on weekends.', ex_cn: '我周末和妈妈去购物。' },
  'market': { ex: 'We buy fruit at the market.', ex_cn: '我们在市场买水果。' },
  'money': { ex: 'Save money for the future.', ex_cn: '为将来存钱。' },
  'price': { ex: 'The price of the book is reasonable.', ex_cn: '这本书的价格很合理。' },
  'cheap': { ex: 'This pen is very cheap.', ex_cn: '这支钢笔很便宜。' },
  'expensive': { ex: 'The watch is too expensive for me.', ex_cn: '这块表对我来说太贵了。' },
  'free': { ex: 'I am free this weekend.', ex_cn: '我这个周末有空。' },
  'paper': { ex: 'Please give me a piece of paper.', ex_cn: '请给我一张纸。' },
  'letter': { ex: 'I wrote a letter to my pen pal.', ex_cn: '我给笔友写了一封信。' },
  'word': { ex: 'Look up this word in the dictionary.', ex_cn: '在词典里查这个词。' },
  'name': { ex: 'My name is Wang Xiaoming.', ex_cn: '我的名字是王小明。' },
  'number': { ex: 'What is your phone number?', ex_cn: '你的电话号码是多少？' },
  'question': { ex: 'Do you have any questions?', ex_cn: '你有什么问题吗？' },
  'idea': { ex: 'That is a wonderful idea!', ex_cn: '那是一个绝妙的主意！' },
  'example': { ex: 'Can you give me an example?', ex_cn: '你能给我举个例子吗？' },
  'place': { ex: 'This is a good place for a picnic.', ex_cn: '这是一个野餐的好地方。' },
  'home': { ex: 'I go home after school.', ex_cn: '我放学后回家。' },
  'family': { ex: 'There are four people in my family.', ex_cn: '我家有四口人。' },
  'person': { ex: 'She is a kind person.', ex_cn: '她是一个善良的人。' },
  'thing': { ex: 'The first thing I do is brush my teeth.', ex_cn: '我做的第一件事是刷牙。' },
  'part': { ex: 'I want to take part in the school play.', ex_cn: '我想参加学校的戏剧演出。' },
  'kind': { ex: 'She is a kind and helpful person.', ex_cn: '她是一个善良且乐于助人的人。' },
  'lot': { ex: 'There are a lot of books in the library.', ex_cn: '图书馆里有很多书。' },
  'enough': { ex: 'We have enough time to finish the work.', ex_cn: '我们有足够的时间完成工作。' },
  'such': { ex: 'It was such a beautiful day that we went out.', ex_cn: '天气这么好，我们就出去了。' },
  'still': { ex: 'I still remember my first day at school.', ex_cn: '我仍然记得我上学的第一天。' },
  'always': { ex: 'She always helps others when they need help.', ex_cn: '她总是在别人需要帮助时伸出援手。' },
  'never': { ex: 'I have never been to Beijing.', ex_cn: '我从未去过北京。' },
  'often': { ex: 'I often read books before going to bed.', ex_cn: '我经常在睡觉前读书。' },
  'usually': { ex: 'I usually get up at seven in the morning.', ex_cn: '我通常早上七点起床。' },
  'sometimes': { ex: 'Sometimes I walk to school.', ex_cn: '有时候我步行去上学。' },
  'seldom': { ex: 'I seldom eat fast food.', ex_cn: '我很少吃快餐。' },
  'already': { ex: 'I have already finished my homework.', ex_cn: '我已经完成了作业。' },
  'yet': { ex: 'I have not finished my homework yet.', ex_cn: '我还没有完成作业。' },
  'once': { ex: 'I have been to Shanghai once.', ex_cn: '我去过上海一次。' },
  'since': { ex: 'I have studied English since 2020.', ex_cn: '我从2020年开始学英语。' },
  'ago': { ex: 'I moved to this city two years ago.', ex_cn: '我两年前搬到了这个城市。' },
  'before': { ex: 'Wash your hands before eating.', ex_cn: '吃饭前要洗手。' },
  'during': { ex: 'We had a test during the class.', ex_cn: '上课期间我们有一个小测。' },
  'until': { ex: 'I will wait here until you come back.', ex_cn: '我会在这里等你回来。' },
  'while': { ex: 'I listened to music while doing homework.', ex_cn: '我做作业时听音乐。' },
  'although': { ex: 'Although it rained, we still went out to play.', ex_cn: '虽然下雨了，我们还是出去玩了。' },
  'where': { ex: 'Where do you live?', ex_cn: '你住在哪里？' },
  'why': { ex: 'Why are you late for school?', ex_cn: '你为什么上学迟到？' },
  'whom': { ex: 'Whom did you meet yesterday?', ex_cn: '你昨天遇见了谁？' },
  'whose': { ex: 'Whose bag is this?', ex_cn: '这是谁的包？' },
  'that': { ex: 'The book that I read is very interesting.', ex_cn: '我读的那本书非常有趣。' },
  'those': { ex: 'Those apples are very sweet.', ex_cn: '那些苹果很甜。' },
  'here': { ex: 'Here is your book.', ex_cn: '这是你的书。' },
  'everywhere': { ex: 'I looked everywhere for my keys.', ex_cn: '我到处找了钥匙。' },
  'somewhere': { ex: 'I left my phone somewhere in the house.', ex_cn: '我把手机落在房子的某个地方了。' },
  'anywhere': { ex: 'I cannot find my pen anywhere.', ex_cn: '我到处都找不到我的钢笔。' },
  'everyone': { ex: 'Everyone in our class likes English.', ex_cn: '我们班每个人都喜欢英语。' },
  'someone': { ex: 'Someone is waiting for you at the door.', ex_cn: '有人在门口等你。' },
  'anyone': { ex: 'Does anyone know the answer?', ex_cn: '有人知道答案吗？' },
  'everything': { ex: 'Everything is ready for the party.', ex_cn: '派对的一切都准备好了。' },
  'something': { ex: 'I have something important to tell you.', ex_cn: '我有重要的事情要告诉你。' },
  'nothing': { ex: 'There is nothing to worry about.', ex_cn: '没什么可担心的。' },
  'myself': { ex: 'I made this card by myself.', ex_cn: '我亲手做了这张卡片。' },
  'yourself': { ex: 'Help yourself to some fruit.', ex_cn: '请随便吃点水果。' },
  'himself': { ex: 'He taught himself to play the guitar.', ex_cn: '他自学了弹吉他。' },
  'herself': { ex: 'She cooked dinner by herself.', ex_cn: '她独自做了晚饭。' },
  'itself': { ex: 'The door closed by itself.', ex_cn: '门自己关上了。' },
  'ourselves': { ex: 'We enjoyed ourselves at the party.', ex_cn: '我们在派对上玩得很开心。' },
  'yourselves': { ex: 'Please behave yourselves in class.', ex_cn: '请在课堂上表现好。' },
  'themselves': { ex: 'They taught themselves English.', ex_cn: '他们自学了英语。' },
};

// Process line by line
let lineCount = 0;
let entryRegex = /^\s*\{'e':\s*'([^']*?)'/;

for (let i = 0; i < lines.length; i++) {
  let line = lines[i];
  let trimmedLine = line.trim();
  
  const entryMatch = trimmedLine.match(entryRegex);
  
  if (entryMatch && (trimmedLine.endsWith('},') || trimmedLine.endsWith('}'))) {
    const english = entryMatch[1];
    lineCount++;
    
    // Find the closing of the map: we need to insert before the closing '}'
    const lastCloseBrace = line.lastIndexOf('}');
    const beforeClose = line.substring(0, lastCloseBrace);
    const afterClose = line.substring(lastCloseBrace);  // '},' or '}'
    
    let exText, exCnText;
    if (examples[english]) {
      exText = examples[english].ex;
      exCnText = examples[english].ex_cn;
    } else {
      // Fallback sentence
      exText = `This is a good example of "${english}".`;
      exCnText = `这是"${english}"的一个好例子。`;
    }
    
    // Escape single quotes in the example sentences
    const exEscaped = exText.replace(/'/g, "\\'");
    const exCnEscaped = exCnText.replace(/'/g, "\\'");
    
    const newLine = beforeClose + `, 'ex': '${exEscaped}', 'ex_cn': '${exCnEscaped}'` + afterClose;
    result.push(newLine);
  } else {
    result.push(line);
  }
}

// Write the result
fs.writeFileSync(filePath, result.join('\n'), 'utf8');

console.log(`Processed ${lineCount} word entries.`);
console.log('Done! Example sentences added successfully.');
